/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppServersRouteImport } from './routes/_app.servers'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppNodesIndexRouteImport } from './routes/_app.nodes.index'
import { Route as AppNetworksIndexRouteImport } from './routes/_app.networks.index'
import { Route as AppAccountIndexRouteImport } from './routes/_app.account.index'
import { Route as AppSettingsMembersRouteImport } from './routes/_app.settings.members'
import { Route as AppSettingsActivityRouteImport } from './routes/_app.settings.activity'
import { Route as AppNodesNodeIdRouteImport } from './routes/_app.nodes.$nodeId'
import { Route as AppNetworksNetworkIdRouteImport } from './routes/_app.networks.$networkId'
import { Route as AppAccountSshKeysRouteImport } from './routes/_app.account.ssh-keys'
import { Route as AppAccountActivityRouteImport } from './routes/_app.account.activity'
import { Route as AppNodesNodeIdIndexRouteImport } from './routes/_app.nodes.$nodeId.index'
import { Route as AppNodesNodeIdStorageRouteImport } from './routes/_app.nodes.$nodeId.storage'
import { Route as AppNodesNodeIdSettingsRouteImport } from './routes/_app.nodes.$nodeId.settings'
import { Route as AppNodesNodeIdNetworkingRouteImport } from './routes/_app.nodes.$nodeId.networking'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServersRoute = AppServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppNodesIndexRoute = AppNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworksIndexRoute = AppNetworksIndexRouteImport.update({
  id: '/networks/',
  path: '/networks/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsActivityRoute = AppSettingsActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppNodesNodeIdRoute = AppNodesNodeIdRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworksNetworkIdRoute = AppNetworksNetworkIdRouteImport.update({
  id: '/networks/$networkId',
  path: '/networks/$networkId',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountSshKeysRoute = AppAccountSshKeysRouteImport.update({
  id: '/ssh-keys',
  path: '/ssh-keys',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountActivityRoute = AppAccountActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppNodesNodeIdIndexRoute = AppNodesNodeIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNodesNodeIdRoute,
} as any)
const AppNodesNodeIdStorageRoute = AppNodesNodeIdStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AppNodesNodeIdRoute,
} as any)
const AppNodesNodeIdSettingsRoute = AppNodesNodeIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppNodesNodeIdRoute,
} as any)
const AppNodesNodeIdNetworkingRoute =
  AppNodesNodeIdNetworkingRouteImport.update({
    id: '/networking',
    path: '/networking',
    getParentRoute: () => AppNodesNodeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/account': typeof AppAccountRouteWithChildren
  '/servers': typeof AppServersRoute
  '/settings': typeof AppSettingsRouteWithChildren
  '/templates': typeof AppTemplatesRoute
  '/account/activity': typeof AppAccountActivityRoute
  '/account/ssh-keys': typeof AppAccountSshKeysRoute
  '/networks/$networkId': typeof AppNetworksNetworkIdRoute
  '/nodes/$nodeId': typeof AppNodesNodeIdRouteWithChildren
  '/settings/activity': typeof AppSettingsActivityRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/account/': typeof AppAccountIndexRoute
  '/networks/': typeof AppNetworksIndexRoute
  '/nodes/': typeof AppNodesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/nodes/$nodeId/networking': typeof AppNodesNodeIdNetworkingRoute
  '/nodes/$nodeId/settings': typeof AppNodesNodeIdSettingsRoute
  '/nodes/$nodeId/storage': typeof AppNodesNodeIdStorageRoute
  '/nodes/$nodeId/': typeof AppNodesNodeIdIndexRoute
}
export interface FileRoutesByTo {
  '/servers': typeof AppServersRoute
  '/templates': typeof AppTemplatesRoute
  '/': typeof AppIndexRoute
  '/account/activity': typeof AppAccountActivityRoute
  '/account/ssh-keys': typeof AppAccountSshKeysRoute
  '/networks/$networkId': typeof AppNetworksNetworkIdRoute
  '/settings/activity': typeof AppSettingsActivityRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/account': typeof AppAccountIndexRoute
  '/networks': typeof AppNetworksIndexRoute
  '/nodes': typeof AppNodesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/nodes/$nodeId/networking': typeof AppNodesNodeIdNetworkingRoute
  '/nodes/$nodeId/settings': typeof AppNodesNodeIdSettingsRoute
  '/nodes/$nodeId/storage': typeof AppNodesNodeIdStorageRoute
  '/nodes/$nodeId': typeof AppNodesNodeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/account': typeof AppAccountRouteWithChildren
  '/_app/servers': typeof AppServersRoute
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/templates': typeof AppTemplatesRoute
  '/_app/': typeof AppIndexRoute
  '/_app/account/activity': typeof AppAccountActivityRoute
  '/_app/account/ssh-keys': typeof AppAccountSshKeysRoute
  '/_app/networks/$networkId': typeof AppNetworksNetworkIdRoute
  '/_app/nodes/$nodeId': typeof AppNodesNodeIdRouteWithChildren
  '/_app/settings/activity': typeof AppSettingsActivityRoute
  '/_app/settings/members': typeof AppSettingsMembersRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/_app/networks/': typeof AppNetworksIndexRoute
  '/_app/nodes/': typeof AppNodesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/nodes/$nodeId/networking': typeof AppNodesNodeIdNetworkingRoute
  '/_app/nodes/$nodeId/settings': typeof AppNodesNodeIdSettingsRoute
  '/_app/nodes/$nodeId/storage': typeof AppNodesNodeIdStorageRoute
  '/_app/nodes/$nodeId/': typeof AppNodesNodeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/servers'
    | '/settings'
    | '/templates'
    | '/account/activity'
    | '/account/ssh-keys'
    | '/networks/$networkId'
    | '/nodes/$nodeId'
    | '/settings/activity'
    | '/settings/members'
    | '/account/'
    | '/networks/'
    | '/nodes/'
    | '/settings/'
    | '/nodes/$nodeId/networking'
    | '/nodes/$nodeId/settings'
    | '/nodes/$nodeId/storage'
    | '/nodes/$nodeId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/servers'
    | '/templates'
    | '/'
    | '/account/activity'
    | '/account/ssh-keys'
    | '/networks/$networkId'
    | '/settings/activity'
    | '/settings/members'
    | '/account'
    | '/networks'
    | '/nodes'
    | '/settings'
    | '/nodes/$nodeId/networking'
    | '/nodes/$nodeId/settings'
    | '/nodes/$nodeId/storage'
    | '/nodes/$nodeId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/account'
    | '/_app/servers'
    | '/_app/settings'
    | '/_app/templates'
    | '/_app/'
    | '/_app/account/activity'
    | '/_app/account/ssh-keys'
    | '/_app/networks/$networkId'
    | '/_app/nodes/$nodeId'
    | '/_app/settings/activity'
    | '/_app/settings/members'
    | '/_app/account/'
    | '/_app/networks/'
    | '/_app/nodes/'
    | '/_app/settings/'
    | '/_app/nodes/$nodeId/networking'
    | '/_app/nodes/$nodeId/settings'
    | '/_app/nodes/$nodeId/storage'
    | '/_app/nodes/$nodeId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers': {
      id: '/_app/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AppServersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/nodes/': {
      id: '/_app/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof AppNodesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/networks/': {
      id: '/_app/networks/'
      path: '/networks'
      fullPath: '/networks/'
      preLoaderRoute: typeof AppNetworksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/settings/members': {
      id: '/_app/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/activity': {
      id: '/_app/settings/activity'
      path: '/activity'
      fullPath: '/settings/activity'
      preLoaderRoute: typeof AppSettingsActivityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/nodes/$nodeId': {
      id: '/_app/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/nodes/$nodeId'
      preLoaderRoute: typeof AppNodesNodeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/networks/$networkId': {
      id: '/_app/networks/$networkId'
      path: '/networks/$networkId'
      fullPath: '/networks/$networkId'
      preLoaderRoute: typeof AppNetworksNetworkIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/ssh-keys': {
      id: '/_app/account/ssh-keys'
      path: '/ssh-keys'
      fullPath: '/account/ssh-keys'
      preLoaderRoute: typeof AppAccountSshKeysRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/activity': {
      id: '/_app/account/activity'
      path: '/activity'
      fullPath: '/account/activity'
      preLoaderRoute: typeof AppAccountActivityRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/nodes/$nodeId/': {
      id: '/_app/nodes/$nodeId/'
      path: '/'
      fullPath: '/nodes/$nodeId/'
      preLoaderRoute: typeof AppNodesNodeIdIndexRouteImport
      parentRoute: typeof AppNodesNodeIdRoute
    }
    '/_app/nodes/$nodeId/storage': {
      id: '/_app/nodes/$nodeId/storage'
      path: '/storage'
      fullPath: '/nodes/$nodeId/storage'
      preLoaderRoute: typeof AppNodesNodeIdStorageRouteImport
      parentRoute: typeof AppNodesNodeIdRoute
    }
    '/_app/nodes/$nodeId/settings': {
      id: '/_app/nodes/$nodeId/settings'
      path: '/settings'
      fullPath: '/nodes/$nodeId/settings'
      preLoaderRoute: typeof AppNodesNodeIdSettingsRouteImport
      parentRoute: typeof AppNodesNodeIdRoute
    }
    '/_app/nodes/$nodeId/networking': {
      id: '/_app/nodes/$nodeId/networking'
      path: '/networking'
      fullPath: '/nodes/$nodeId/networking'
      preLoaderRoute: typeof AppNodesNodeIdNetworkingRouteImport
      parentRoute: typeof AppNodesNodeIdRoute
    }
  }
}

interface AppAccountRouteChildren {
  AppAccountActivityRoute: typeof AppAccountActivityRoute
  AppAccountSshKeysRoute: typeof AppAccountSshKeysRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppAccountRouteChildren: AppAccountRouteChildren = {
  AppAccountActivityRoute: AppAccountActivityRoute,
  AppAccountSshKeysRoute: AppAccountSshKeysRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppAccountRouteWithChildren = AppAccountRoute._addFileChildren(
  AppAccountRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsActivityRoute: typeof AppSettingsActivityRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsActivityRoute: AppSettingsActivityRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppNodesNodeIdRouteChildren {
  AppNodesNodeIdNetworkingRoute: typeof AppNodesNodeIdNetworkingRoute
  AppNodesNodeIdSettingsRoute: typeof AppNodesNodeIdSettingsRoute
  AppNodesNodeIdStorageRoute: typeof AppNodesNodeIdStorageRoute
  AppNodesNodeIdIndexRoute: typeof AppNodesNodeIdIndexRoute
}

const AppNodesNodeIdRouteChildren: AppNodesNodeIdRouteChildren = {
  AppNodesNodeIdNetworkingRoute: AppNodesNodeIdNetworkingRoute,
  AppNodesNodeIdSettingsRoute: AppNodesNodeIdSettingsRoute,
  AppNodesNodeIdStorageRoute: AppNodesNodeIdStorageRoute,
  AppNodesNodeIdIndexRoute: AppNodesNodeIdIndexRoute,
}

const AppNodesNodeIdRouteWithChildren = AppNodesNodeIdRoute._addFileChildren(
  AppNodesNodeIdRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRouteWithChildren
  AppServersRoute: typeof AppServersRoute
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppNetworksNetworkIdRoute: typeof AppNetworksNetworkIdRoute
  AppNodesNodeIdRoute: typeof AppNodesNodeIdRouteWithChildren
  AppNetworksIndexRoute: typeof AppNetworksIndexRoute
  AppNodesIndexRoute: typeof AppNodesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRouteWithChildren,
  AppServersRoute: AppServersRoute,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
  AppNetworksNetworkIdRoute: AppNetworksNetworkIdRoute,
  AppNodesNodeIdRoute: AppNodesNodeIdRouteWithChildren,
  AppNetworksIndexRoute: AppNetworksIndexRoute,
  AppNodesIndexRoute: AppNodesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
