/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AppTemplatesRouteImport } from './routes/_app.templates'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminTemplatesIndexRouteImport } from './routes/admin.templates.index'
import { Route as AdminSubdomainsIndexRouteImport } from './routes/admin.subdomains.index'
import { Route as AdminOrgsIndexRouteImport } from './routes/admin.orgs.index'
import { Route as AdminNodesIndexRouteImport } from './routes/admin.nodes.index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppServersIndexRouteImport } from './routes/_app.servers.index'
import { Route as AppNodesIndexRouteImport } from './routes/_app.nodes.index'
import { Route as AppNetworksIndexRouteImport } from './routes/_app.networks.index'
import { Route as AppAccountIndexRouteImport } from './routes/_app.account.index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin.users.$userId'
import { Route as AdminTemplatesNewRouteImport } from './routes/admin.templates.new'
import { Route as AdminTemplatesTemplateIdRouteImport } from './routes/admin.templates.$templateId'
import { Route as AdminOrgsOrgIdRouteImport } from './routes/admin.orgs.$orgId'
import { Route as AdminNodesNodeIdRouteImport } from './routes/admin.nodes.$nodeId'
import { Route as AppTemplatesNewRouteImport } from './routes/_app.templates_.new'
import { Route as AppTemplatesTemplateIdRouteImport } from './routes/_app.templates_.$templateId'
import { Route as AppSettingsMembersRouteImport } from './routes/_app.settings.members'
import { Route as AppSettingsBillingRouteImport } from './routes/_app.settings.billing'
import { Route as AppSettingsActivityRouteImport } from './routes/_app.settings.activity'
import { Route as AppServersNewRouteImport } from './routes/_app.servers.new'
import { Route as AppServersServerIdRouteImport } from './routes/_app.servers.$serverId'
import { Route as AppNodesNewRouteImport } from './routes/_app.nodes.new'
import { Route as AppNodesNodeIdRouteImport } from './routes/_app.nodes.$nodeId'
import { Route as AppNetworksNetworkIdRouteImport } from './routes/_app.networks.$networkId'
import { Route as AppAccountActivityRouteImport } from './routes/_app.account.activity'
import { Route as AppServersServerIdIndexRouteImport } from './routes/_app.servers.$serverId.index'
import { Route as AppNodesNodeIdIndexRouteImport } from './routes/_app.nodes.$nodeId.index'
import { Route as AdminTemplatesTemplateIdEditRouteImport } from './routes/admin.templates.$templateId_.edit'
import { Route as AppTemplatesTemplateIdEditRouteImport } from './routes/_app.templates_.$templateId_.edit'
import { Route as AppServersServerIdStartupRouteImport } from './routes/_app.servers.$serverId.startup'
import { Route as AppServersServerIdSettingsRouteImport } from './routes/_app.servers.$serverId.settings'
import { Route as AppServersServerIdSchedulesRouteImport } from './routes/_app.servers.$serverId.schedules'
import { Route as AppServersServerIdNetworkRouteImport } from './routes/_app.servers.$serverId.network'
import { Route as AppServersServerIdFilesRouteImport } from './routes/_app.servers.$serverId.files'
import { Route as AppServersServerIdDatabaseRouteImport } from './routes/_app.servers.$serverId.database'
import { Route as AppServersServerIdBackupsRouteImport } from './routes/_app.servers.$serverId.backups'
import { Route as AppServersServerIdActivityRouteImport } from './routes/_app.servers.$serverId.activity'
import { Route as AppNodesNodeIdStorageRouteImport } from './routes/_app.nodes.$nodeId.storage'
import { Route as AppNodesNodeIdSettingsRouteImport } from './routes/_app.nodes.$nodeId.settings'
import { Route as AppNodesNodeIdNetworkingRouteImport } from './routes/_app.nodes.$nodeId.networking'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesIndexRoute = AdminTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubdomainsIndexRoute = AdminSubdomainsIndexRouteImport.update({
  id: '/subdomains/',
  path: '/subdomains/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrgsIndexRoute = AdminOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNodesIndexRoute = AdminNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => AdminRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppServersIndexRoute = AppServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => AppRoute,
} as any)
const AppNodesIndexRoute = AppNodesIndexRouteImport.update({
  id: '/nodes/',
  path: '/nodes/',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworksIndexRoute = AppNetworksIndexRouteImport.update({
  id: '/networks/',
  path: '/networks/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesNewRoute = AdminTemplatesNewRouteImport.update({
  id: '/templates/new',
  path: '/templates/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplatesTemplateIdRoute =
  AdminTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrgsOrgIdRoute = AdminOrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNodesNodeIdRoute = AdminNodesNodeIdRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => AdminRoute,
} as any)
const AppTemplatesNewRoute = AppTemplatesNewRouteImport.update({
  id: '/templates_/new',
  path: '/templates/new',
  getParentRoute: () => AppRoute,
} as any)
const AppTemplatesTemplateIdRoute = AppTemplatesTemplateIdRouteImport.update({
  id: '/templates_/$templateId',
  path: '/templates/$templateId',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsActivityRoute = AppSettingsActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppServersNewRoute = AppServersNewRouteImport.update({
  id: '/servers/new',
  path: '/servers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppServersServerIdRoute = AppServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => AppRoute,
} as any)
const AppNodesNewRoute = AppNodesNewRouteImport.update({
  id: '/nodes/new',
  path: '/nodes/new',
  getParentRoute: () => AppRoute,
} as any)
const AppNodesNodeIdRoute = AppNodesNodeIdRouteImport.update({
  id: '/nodes/$nodeId',
  path: '/nodes/$nodeId',
  getParentRoute: () => AppRoute,
} as any)
const AppNetworksNetworkIdRoute = AppNetworksNetworkIdRouteImport.update({
  id: '/networks/$networkId',
  path: '/networks/$networkId',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountActivityRoute = AppAccountActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppServersServerIdIndexRoute = AppServersServerIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppServersServerIdRoute,
} as any)
const AppNodesNodeIdIndexRoute = AppNodesNodeIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppNodesNodeIdRoute,
} as any)
const AdminTemplatesTemplateIdEditRoute =
  AdminTemplatesTemplateIdEditRouteImport.update({
    id: '/templates/$templateId_/edit',
    path: '/templates/$templateId/edit',
    getParentRoute: () => AdminRoute,
  } as any)
const AppTemplatesTemplateIdEditRoute =
  AppTemplatesTemplateIdEditRouteImport.update({
    id: '/templates_/$templateId_/edit',
    path: '/templates/$templateId/edit',
    getParentRoute: () => AppRoute,
  } as any)
const AppServersServerIdStartupRoute =
  AppServersServerIdStartupRouteImport.update({
    id: '/startup',
    path: '/startup',
    getParentRoute: () => AppServersServerIdRoute,
  } as any)
const AppServersServerIdSettingsRoute =
  AppServersServerIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppServersServerIdRoute,
  } as any)
const AppServersServerIdSchedulesRoute =
  AppServersServerIdSchedulesRouteImport.update({
    id: '/schedules',
    path: '/schedules',
    getParentRoute: () => AppServersServerIdRoute,
  } as any)
const AppServersServerIdNetworkRoute =
  AppServersServerIdNetworkRouteImport.update({
    id: '/network',
    path: '/network',
    getParentRoute: () => AppServersServerIdRoute,
  } as any)
const AppServersServerIdFilesRoute = AppServersServerIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppServersServerIdRoute,
} as any)
const AppServersServerIdDatabaseRoute =
  AppServersServerIdDatabaseRouteImport.update({
    id: '/database',
    path: '/database',
    getParentRoute: () => AppServersServerIdRoute,
  } as any)
const AppServersServerIdBackupsRoute =
  AppServersServerIdBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => AppServersServerIdRoute,
  } as any)
const AppServersServerIdActivityRoute =
  AppServersServerIdActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AppServersServerIdRoute,
  } as any)
const AppNodesNodeIdStorageRoute = AppNodesNodeIdStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AppNodesNodeIdRoute,
} as any)
const AppNodesNodeIdSettingsRoute = AppNodesNodeIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppNodesNodeIdRoute,
} as any)
const AppNodesNodeIdNetworkingRoute =
  AppNodesNodeIdNetworkingRouteImport.update({
    id: '/networking',
    path: '/networking',
    getParentRoute: () => AppNodesNodeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/account': typeof AppAccountRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/templates': typeof AppTemplatesRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/account/activity': typeof AppAccountActivityRoute
  '/networks/$networkId': typeof AppNetworksNetworkIdRoute
  '/nodes/$nodeId': typeof AppNodesNodeIdRouteWithChildren
  '/nodes/new': typeof AppNodesNewRoute
  '/servers/$serverId': typeof AppServersServerIdRouteWithChildren
  '/servers/new': typeof AppServersNewRoute
  '/settings/activity': typeof AppSettingsActivityRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/templates/new': typeof AppTemplatesNewRoute
  '/admin/nodes/$nodeId': typeof AdminNodesNodeIdRoute
  '/admin/orgs/$orgId': typeof AdminOrgsOrgIdRoute
  '/admin/templates/$templateId': typeof AdminTemplatesTemplateIdRoute
  '/admin/templates/new': typeof AdminTemplatesNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/account/': typeof AppAccountIndexRoute
  '/networks/': typeof AppNetworksIndexRoute
  '/nodes/': typeof AppNodesIndexRoute
  '/servers/': typeof AppServersIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/admin/nodes/': typeof AdminNodesIndexRoute
  '/admin/orgs/': typeof AdminOrgsIndexRoute
  '/admin/subdomains/': typeof AdminSubdomainsIndexRoute
  '/admin/templates/': typeof AdminTemplatesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/nodes/$nodeId/networking': typeof AppNodesNodeIdNetworkingRoute
  '/nodes/$nodeId/settings': typeof AppNodesNodeIdSettingsRoute
  '/nodes/$nodeId/storage': typeof AppNodesNodeIdStorageRoute
  '/servers/$serverId/activity': typeof AppServersServerIdActivityRoute
  '/servers/$serverId/backups': typeof AppServersServerIdBackupsRoute
  '/servers/$serverId/database': typeof AppServersServerIdDatabaseRoute
  '/servers/$serverId/files': typeof AppServersServerIdFilesRoute
  '/servers/$serverId/network': typeof AppServersServerIdNetworkRoute
  '/servers/$serverId/schedules': typeof AppServersServerIdSchedulesRoute
  '/servers/$serverId/settings': typeof AppServersServerIdSettingsRoute
  '/servers/$serverId/startup': typeof AppServersServerIdStartupRoute
  '/templates/$templateId/edit': typeof AppTemplatesTemplateIdEditRoute
  '/admin/templates/$templateId/edit': typeof AdminTemplatesTemplateIdEditRoute
  '/nodes/$nodeId/': typeof AppNodesNodeIdIndexRoute
  '/servers/$serverId/': typeof AppServersServerIdIndexRoute
}
export interface FileRoutesByTo {
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/templates': typeof AppTemplatesRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/account/activity': typeof AppAccountActivityRoute
  '/networks/$networkId': typeof AppNetworksNetworkIdRoute
  '/nodes/new': typeof AppNodesNewRoute
  '/servers/new': typeof AppServersNewRoute
  '/settings/activity': typeof AppSettingsActivityRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/templates/$templateId': typeof AppTemplatesTemplateIdRoute
  '/templates/new': typeof AppTemplatesNewRoute
  '/admin/nodes/$nodeId': typeof AdminNodesNodeIdRoute
  '/admin/orgs/$orgId': typeof AdminOrgsOrgIdRoute
  '/admin/templates/$templateId': typeof AdminTemplatesTemplateIdRoute
  '/admin/templates/new': typeof AdminTemplatesNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/account': typeof AppAccountIndexRoute
  '/networks': typeof AppNetworksIndexRoute
  '/nodes': typeof AppNodesIndexRoute
  '/servers': typeof AppServersIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/admin/nodes': typeof AdminNodesIndexRoute
  '/admin/orgs': typeof AdminOrgsIndexRoute
  '/admin/subdomains': typeof AdminSubdomainsIndexRoute
  '/admin/templates': typeof AdminTemplatesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/nodes/$nodeId/networking': typeof AppNodesNodeIdNetworkingRoute
  '/nodes/$nodeId/settings': typeof AppNodesNodeIdSettingsRoute
  '/nodes/$nodeId/storage': typeof AppNodesNodeIdStorageRoute
  '/servers/$serverId/activity': typeof AppServersServerIdActivityRoute
  '/servers/$serverId/backups': typeof AppServersServerIdBackupsRoute
  '/servers/$serverId/database': typeof AppServersServerIdDatabaseRoute
  '/servers/$serverId/files': typeof AppServersServerIdFilesRoute
  '/servers/$serverId/network': typeof AppServersServerIdNetworkRoute
  '/servers/$serverId/schedules': typeof AppServersServerIdSchedulesRoute
  '/servers/$serverId/settings': typeof AppServersServerIdSettingsRoute
  '/servers/$serverId/startup': typeof AppServersServerIdStartupRoute
  '/templates/$templateId/edit': typeof AppTemplatesTemplateIdEditRoute
  '/admin/templates/$templateId/edit': typeof AdminTemplatesTemplateIdEditRoute
  '/nodes/$nodeId': typeof AppNodesNodeIdIndexRoute
  '/servers/$serverId': typeof AppServersServerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_app/account': typeof AppAccountRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/templates': typeof AppTemplatesRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/account/activity': typeof AppAccountActivityRoute
  '/_app/networks/$networkId': typeof AppNetworksNetworkIdRoute
  '/_app/nodes/$nodeId': typeof AppNodesNodeIdRouteWithChildren
  '/_app/nodes/new': typeof AppNodesNewRoute
  '/_app/servers/$serverId': typeof AppServersServerIdRouteWithChildren
  '/_app/servers/new': typeof AppServersNewRoute
  '/_app/settings/activity': typeof AppSettingsActivityRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/members': typeof AppSettingsMembersRoute
  '/_app/templates_/$templateId': typeof AppTemplatesTemplateIdRoute
  '/_app/templates_/new': typeof AppTemplatesNewRoute
  '/admin/nodes/$nodeId': typeof AdminNodesNodeIdRoute
  '/admin/orgs/$orgId': typeof AdminOrgsOrgIdRoute
  '/admin/templates/$templateId': typeof AdminTemplatesTemplateIdRoute
  '/admin/templates/new': typeof AdminTemplatesNewRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/_app/networks/': typeof AppNetworksIndexRoute
  '/_app/nodes/': typeof AppNodesIndexRoute
  '/_app/servers/': typeof AppServersIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/admin/nodes/': typeof AdminNodesIndexRoute
  '/admin/orgs/': typeof AdminOrgsIndexRoute
  '/admin/subdomains/': typeof AdminSubdomainsIndexRoute
  '/admin/templates/': typeof AdminTemplatesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/_app/nodes/$nodeId/networking': typeof AppNodesNodeIdNetworkingRoute
  '/_app/nodes/$nodeId/settings': typeof AppNodesNodeIdSettingsRoute
  '/_app/nodes/$nodeId/storage': typeof AppNodesNodeIdStorageRoute
  '/_app/servers/$serverId/activity': typeof AppServersServerIdActivityRoute
  '/_app/servers/$serverId/backups': typeof AppServersServerIdBackupsRoute
  '/_app/servers/$serverId/database': typeof AppServersServerIdDatabaseRoute
  '/_app/servers/$serverId/files': typeof AppServersServerIdFilesRoute
  '/_app/servers/$serverId/network': typeof AppServersServerIdNetworkRoute
  '/_app/servers/$serverId/schedules': typeof AppServersServerIdSchedulesRoute
  '/_app/servers/$serverId/settings': typeof AppServersServerIdSettingsRoute
  '/_app/servers/$serverId/startup': typeof AppServersServerIdStartupRoute
  '/_app/templates_/$templateId_/edit': typeof AppTemplatesTemplateIdEditRoute
  '/admin/templates/$templateId_/edit': typeof AdminTemplatesTemplateIdEditRoute
  '/_app/nodes/$nodeId/': typeof AppNodesNodeIdIndexRoute
  '/_app/servers/$serverId/': typeof AppServersServerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/account'
    | '/settings'
    | '/templates'
    | '/admin/activity'
    | '/admin/billing'
    | '/admin/settings'
    | '/admin/'
    | '/account/activity'
    | '/networks/$networkId'
    | '/nodes/$nodeId'
    | '/nodes/new'
    | '/servers/$serverId'
    | '/servers/new'
    | '/settings/activity'
    | '/settings/billing'
    | '/settings/members'
    | '/templates/$templateId'
    | '/templates/new'
    | '/admin/nodes/$nodeId'
    | '/admin/orgs/$orgId'
    | '/admin/templates/$templateId'
    | '/admin/templates/new'
    | '/admin/users/$userId'
    | '/account/'
    | '/networks/'
    | '/nodes/'
    | '/servers/'
    | '/settings/'
    | '/admin/nodes/'
    | '/admin/orgs/'
    | '/admin/subdomains/'
    | '/admin/templates/'
    | '/admin/users/'
    | '/nodes/$nodeId/networking'
    | '/nodes/$nodeId/settings'
    | '/nodes/$nodeId/storage'
    | '/servers/$serverId/activity'
    | '/servers/$serverId/backups'
    | '/servers/$serverId/database'
    | '/servers/$serverId/files'
    | '/servers/$serverId/network'
    | '/servers/$serverId/schedules'
    | '/servers/$serverId/settings'
    | '/servers/$serverId/startup'
    | '/templates/$templateId/edit'
    | '/admin/templates/$templateId/edit'
    | '/nodes/$nodeId/'
    | '/servers/$serverId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/home'
    | '/login'
    | '/onboarding'
    | '/templates'
    | '/admin/activity'
    | '/admin/billing'
    | '/admin/settings'
    | '/'
    | '/admin'
    | '/account/activity'
    | '/networks/$networkId'
    | '/nodes/new'
    | '/servers/new'
    | '/settings/activity'
    | '/settings/billing'
    | '/settings/members'
    | '/templates/$templateId'
    | '/templates/new'
    | '/admin/nodes/$nodeId'
    | '/admin/orgs/$orgId'
    | '/admin/templates/$templateId'
    | '/admin/templates/new'
    | '/admin/users/$userId'
    | '/account'
    | '/networks'
    | '/nodes'
    | '/servers'
    | '/settings'
    | '/admin/nodes'
    | '/admin/orgs'
    | '/admin/subdomains'
    | '/admin/templates'
    | '/admin/users'
    | '/nodes/$nodeId/networking'
    | '/nodes/$nodeId/settings'
    | '/nodes/$nodeId/storage'
    | '/servers/$serverId/activity'
    | '/servers/$serverId/backups'
    | '/servers/$serverId/database'
    | '/servers/$serverId/files'
    | '/servers/$serverId/network'
    | '/servers/$serverId/schedules'
    | '/servers/$serverId/settings'
    | '/servers/$serverId/startup'
    | '/templates/$templateId/edit'
    | '/admin/templates/$templateId/edit'
    | '/nodes/$nodeId'
    | '/servers/$serverId'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/home'
    | '/login'
    | '/onboarding'
    | '/_app/account'
    | '/_app/settings'
    | '/_app/templates'
    | '/admin/activity'
    | '/admin/billing'
    | '/admin/settings'
    | '/_app/'
    | '/admin/'
    | '/_app/account/activity'
    | '/_app/networks/$networkId'
    | '/_app/nodes/$nodeId'
    | '/_app/nodes/new'
    | '/_app/servers/$serverId'
    | '/_app/servers/new'
    | '/_app/settings/activity'
    | '/_app/settings/billing'
    | '/_app/settings/members'
    | '/_app/templates_/$templateId'
    | '/_app/templates_/new'
    | '/admin/nodes/$nodeId'
    | '/admin/orgs/$orgId'
    | '/admin/templates/$templateId'
    | '/admin/templates/new'
    | '/admin/users/$userId'
    | '/_app/account/'
    | '/_app/networks/'
    | '/_app/nodes/'
    | '/_app/servers/'
    | '/_app/settings/'
    | '/admin/nodes/'
    | '/admin/orgs/'
    | '/admin/subdomains/'
    | '/admin/templates/'
    | '/admin/users/'
    | '/_app/nodes/$nodeId/networking'
    | '/_app/nodes/$nodeId/settings'
    | '/_app/nodes/$nodeId/storage'
    | '/_app/servers/$serverId/activity'
    | '/_app/servers/$serverId/backups'
    | '/_app/servers/$serverId/database'
    | '/_app/servers/$serverId/files'
    | '/_app/servers/$serverId/network'
    | '/_app/servers/$serverId/schedules'
    | '/_app/servers/$serverId/settings'
    | '/_app/servers/$serverId/startup'
    | '/_app/templates_/$templateId_/edit'
    | '/admin/templates/$templateId_/edit'
    | '/_app/nodes/$nodeId/'
    | '/_app/servers/$serverId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/templates': {
      id: '/_app/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates/': {
      id: '/admin/templates/'
      path: '/templates'
      fullPath: '/admin/templates/'
      preLoaderRoute: typeof AdminTemplatesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subdomains/': {
      id: '/admin/subdomains/'
      path: '/subdomains'
      fullPath: '/admin/subdomains/'
      preLoaderRoute: typeof AdminSubdomainsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orgs/': {
      id: '/admin/orgs/'
      path: '/orgs'
      fullPath: '/admin/orgs/'
      preLoaderRoute: typeof AdminOrgsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nodes/': {
      id: '/admin/nodes/'
      path: '/nodes'
      fullPath: '/admin/nodes/'
      preLoaderRoute: typeof AdminNodesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/servers/': {
      id: '/_app/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof AppServersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodes/': {
      id: '/_app/nodes/'
      path: '/nodes'
      fullPath: '/nodes/'
      preLoaderRoute: typeof AppNodesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/networks/': {
      id: '/_app/networks/'
      path: '/networks'
      fullPath: '/networks/'
      preLoaderRoute: typeof AppNetworksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates/new': {
      id: '/admin/templates/new'
      path: '/templates/new'
      fullPath: '/admin/templates/new'
      preLoaderRoute: typeof AdminTemplatesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/templates/$templateId': {
      id: '/admin/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/admin/templates/$templateId'
      preLoaderRoute: typeof AdminTemplatesTemplateIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orgs/$orgId': {
      id: '/admin/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/admin/orgs/$orgId'
      preLoaderRoute: typeof AdminOrgsOrgIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/nodes/$nodeId': {
      id: '/admin/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/admin/nodes/$nodeId'
      preLoaderRoute: typeof AdminNodesNodeIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/templates_/new': {
      id: '/_app/templates_/new'
      path: '/templates/new'
      fullPath: '/templates/new'
      preLoaderRoute: typeof AppTemplatesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/templates_/$templateId': {
      id: '/_app/templates_/$templateId'
      path: '/templates/$templateId'
      fullPath: '/templates/$templateId'
      preLoaderRoute: typeof AppTemplatesTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/members': {
      id: '/_app/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/activity': {
      id: '/_app/settings/activity'
      path: '/activity'
      fullPath: '/settings/activity'
      preLoaderRoute: typeof AppSettingsActivityRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/servers/new': {
      id: '/_app/servers/new'
      path: '/servers/new'
      fullPath: '/servers/new'
      preLoaderRoute: typeof AppServersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers/$serverId': {
      id: '/_app/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof AppServersServerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodes/new': {
      id: '/_app/nodes/new'
      path: '/nodes/new'
      fullPath: '/nodes/new'
      preLoaderRoute: typeof AppNodesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nodes/$nodeId': {
      id: '/_app/nodes/$nodeId'
      path: '/nodes/$nodeId'
      fullPath: '/nodes/$nodeId'
      preLoaderRoute: typeof AppNodesNodeIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/networks/$networkId': {
      id: '/_app/networks/$networkId'
      path: '/networks/$networkId'
      fullPath: '/networks/$networkId'
      preLoaderRoute: typeof AppNetworksNetworkIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/activity': {
      id: '/_app/account/activity'
      path: '/activity'
      fullPath: '/account/activity'
      preLoaderRoute: typeof AppAccountActivityRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/servers/$serverId/': {
      id: '/_app/servers/$serverId/'
      path: '/'
      fullPath: '/servers/$serverId/'
      preLoaderRoute: typeof AppServersServerIdIndexRouteImport
      parentRoute: typeof AppServersServerIdRoute
    }
    '/_app/nodes/$nodeId/': {
      id: '/_app/nodes/$nodeId/'
      path: '/'
      fullPath: '/nodes/$nodeId/'
      preLoaderRoute: typeof AppNodesNodeIdIndexRouteImport
      parentRoute: typeof AppNodesNodeIdRoute
    }
    '/admin/templates/$templateId_/edit': {
      id: '/admin/templates/$templateId_/edit'
      path: '/templates/$templateId/edit'
      fullPath: '/admin/templates/$templateId/edit'
      preLoaderRoute: typeof AdminTemplatesTemplateIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/templates_/$templateId_/edit': {
      id: '/_app/templates_/$templateId_/edit'
      path: '/templates/$templateId/edit'
      fullPath: '/templates/$templateId/edit'
      preLoaderRoute: typeof AppTemplatesTemplateIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers/$serverId/startup': {
      id: '/_app/servers/$serverId/startup'
      path: '/startup'
      fullPath: '/servers/$serverId/startup'
      preLoaderRoute: typeof AppServersServerIdStartupRouteImport
      parentRoute: typeof AppServersServerIdRoute
    }
    '/_app/servers/$serverId/settings': {
      id: '/_app/servers/$serverId/settings'
      path: '/settings'
      fullPath: '/servers/$serverId/settings'
      preLoaderRoute: typeof AppServersServerIdSettingsRouteImport
      parentRoute: typeof AppServersServerIdRoute
    }
    '/_app/servers/$serverId/schedules': {
      id: '/_app/servers/$serverId/schedules'
      path: '/schedules'
      fullPath: '/servers/$serverId/schedules'
      preLoaderRoute: typeof AppServersServerIdSchedulesRouteImport
      parentRoute: typeof AppServersServerIdRoute
    }
    '/_app/servers/$serverId/network': {
      id: '/_app/servers/$serverId/network'
      path: '/network'
      fullPath: '/servers/$serverId/network'
      preLoaderRoute: typeof AppServersServerIdNetworkRouteImport
      parentRoute: typeof AppServersServerIdRoute
    }
    '/_app/servers/$serverId/files': {
      id: '/_app/servers/$serverId/files'
      path: '/files'
      fullPath: '/servers/$serverId/files'
      preLoaderRoute: typeof AppServersServerIdFilesRouteImport
      parentRoute: typeof AppServersServerIdRoute
    }
    '/_app/servers/$serverId/database': {
      id: '/_app/servers/$serverId/database'
      path: '/database'
      fullPath: '/servers/$serverId/database'
      preLoaderRoute: typeof AppServersServerIdDatabaseRouteImport
      parentRoute: typeof AppServersServerIdRoute
    }
    '/_app/servers/$serverId/backups': {
      id: '/_app/servers/$serverId/backups'
      path: '/backups'
      fullPath: '/servers/$serverId/backups'
      preLoaderRoute: typeof AppServersServerIdBackupsRouteImport
      parentRoute: typeof AppServersServerIdRoute
    }
    '/_app/servers/$serverId/activity': {
      id: '/_app/servers/$serverId/activity'
      path: '/activity'
      fullPath: '/servers/$serverId/activity'
      preLoaderRoute: typeof AppServersServerIdActivityRouteImport
      parentRoute: typeof AppServersServerIdRoute
    }
    '/_app/nodes/$nodeId/storage': {
      id: '/_app/nodes/$nodeId/storage'
      path: '/storage'
      fullPath: '/nodes/$nodeId/storage'
      preLoaderRoute: typeof AppNodesNodeIdStorageRouteImport
      parentRoute: typeof AppNodesNodeIdRoute
    }
    '/_app/nodes/$nodeId/settings': {
      id: '/_app/nodes/$nodeId/settings'
      path: '/settings'
      fullPath: '/nodes/$nodeId/settings'
      preLoaderRoute: typeof AppNodesNodeIdSettingsRouteImport
      parentRoute: typeof AppNodesNodeIdRoute
    }
    '/_app/nodes/$nodeId/networking': {
      id: '/_app/nodes/$nodeId/networking'
      path: '/networking'
      fullPath: '/nodes/$nodeId/networking'
      preLoaderRoute: typeof AppNodesNodeIdNetworkingRouteImport
      parentRoute: typeof AppNodesNodeIdRoute
    }
  }
}

interface AppAccountRouteChildren {
  AppAccountActivityRoute: typeof AppAccountActivityRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppAccountRouteChildren: AppAccountRouteChildren = {
  AppAccountActivityRoute: AppAccountActivityRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppAccountRouteWithChildren = AppAccountRoute._addFileChildren(
  AppAccountRouteChildren,
)

interface AppSettingsRouteChildren {
  AppSettingsActivityRoute: typeof AppSettingsActivityRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsActivityRoute: AppSettingsActivityRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppNodesNodeIdRouteChildren {
  AppNodesNodeIdNetworkingRoute: typeof AppNodesNodeIdNetworkingRoute
  AppNodesNodeIdSettingsRoute: typeof AppNodesNodeIdSettingsRoute
  AppNodesNodeIdStorageRoute: typeof AppNodesNodeIdStorageRoute
  AppNodesNodeIdIndexRoute: typeof AppNodesNodeIdIndexRoute
}

const AppNodesNodeIdRouteChildren: AppNodesNodeIdRouteChildren = {
  AppNodesNodeIdNetworkingRoute: AppNodesNodeIdNetworkingRoute,
  AppNodesNodeIdSettingsRoute: AppNodesNodeIdSettingsRoute,
  AppNodesNodeIdStorageRoute: AppNodesNodeIdStorageRoute,
  AppNodesNodeIdIndexRoute: AppNodesNodeIdIndexRoute,
}

const AppNodesNodeIdRouteWithChildren = AppNodesNodeIdRoute._addFileChildren(
  AppNodesNodeIdRouteChildren,
)

interface AppServersServerIdRouteChildren {
  AppServersServerIdActivityRoute: typeof AppServersServerIdActivityRoute
  AppServersServerIdBackupsRoute: typeof AppServersServerIdBackupsRoute
  AppServersServerIdDatabaseRoute: typeof AppServersServerIdDatabaseRoute
  AppServersServerIdFilesRoute: typeof AppServersServerIdFilesRoute
  AppServersServerIdNetworkRoute: typeof AppServersServerIdNetworkRoute
  AppServersServerIdSchedulesRoute: typeof AppServersServerIdSchedulesRoute
  AppServersServerIdSettingsRoute: typeof AppServersServerIdSettingsRoute
  AppServersServerIdStartupRoute: typeof AppServersServerIdStartupRoute
  AppServersServerIdIndexRoute: typeof AppServersServerIdIndexRoute
}

const AppServersServerIdRouteChildren: AppServersServerIdRouteChildren = {
  AppServersServerIdActivityRoute: AppServersServerIdActivityRoute,
  AppServersServerIdBackupsRoute: AppServersServerIdBackupsRoute,
  AppServersServerIdDatabaseRoute: AppServersServerIdDatabaseRoute,
  AppServersServerIdFilesRoute: AppServersServerIdFilesRoute,
  AppServersServerIdNetworkRoute: AppServersServerIdNetworkRoute,
  AppServersServerIdSchedulesRoute: AppServersServerIdSchedulesRoute,
  AppServersServerIdSettingsRoute: AppServersServerIdSettingsRoute,
  AppServersServerIdStartupRoute: AppServersServerIdStartupRoute,
  AppServersServerIdIndexRoute: AppServersServerIdIndexRoute,
}

const AppServersServerIdRouteWithChildren =
  AppServersServerIdRoute._addFileChildren(AppServersServerIdRouteChildren)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppNetworksNetworkIdRoute: typeof AppNetworksNetworkIdRoute
  AppNodesNodeIdRoute: typeof AppNodesNodeIdRouteWithChildren
  AppNodesNewRoute: typeof AppNodesNewRoute
  AppServersServerIdRoute: typeof AppServersServerIdRouteWithChildren
  AppServersNewRoute: typeof AppServersNewRoute
  AppTemplatesTemplateIdRoute: typeof AppTemplatesTemplateIdRoute
  AppTemplatesNewRoute: typeof AppTemplatesNewRoute
  AppNetworksIndexRoute: typeof AppNetworksIndexRoute
  AppNodesIndexRoute: typeof AppNodesIndexRoute
  AppServersIndexRoute: typeof AppServersIndexRoute
  AppTemplatesTemplateIdEditRoute: typeof AppTemplatesTemplateIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
  AppNetworksNetworkIdRoute: AppNetworksNetworkIdRoute,
  AppNodesNodeIdRoute: AppNodesNodeIdRouteWithChildren,
  AppNodesNewRoute: AppNodesNewRoute,
  AppServersServerIdRoute: AppServersServerIdRouteWithChildren,
  AppServersNewRoute: AppServersNewRoute,
  AppTemplatesTemplateIdRoute: AppTemplatesTemplateIdRoute,
  AppTemplatesNewRoute: AppTemplatesNewRoute,
  AppNetworksIndexRoute: AppNetworksIndexRoute,
  AppNodesIndexRoute: AppNodesIndexRoute,
  AppServersIndexRoute: AppServersIndexRoute,
  AppTemplatesTemplateIdEditRoute: AppTemplatesTemplateIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminNodesNodeIdRoute: typeof AdminNodesNodeIdRoute
  AdminOrgsOrgIdRoute: typeof AdminOrgsOrgIdRoute
  AdminTemplatesTemplateIdRoute: typeof AdminTemplatesTemplateIdRoute
  AdminTemplatesNewRoute: typeof AdminTemplatesNewRoute
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminNodesIndexRoute: typeof AdminNodesIndexRoute
  AdminOrgsIndexRoute: typeof AdminOrgsIndexRoute
  AdminSubdomainsIndexRoute: typeof AdminSubdomainsIndexRoute
  AdminTemplatesIndexRoute: typeof AdminTemplatesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminTemplatesTemplateIdEditRoute: typeof AdminTemplatesTemplateIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminNodesNodeIdRoute: AdminNodesNodeIdRoute,
  AdminOrgsOrgIdRoute: AdminOrgsOrgIdRoute,
  AdminTemplatesTemplateIdRoute: AdminTemplatesTemplateIdRoute,
  AdminTemplatesNewRoute: AdminTemplatesNewRoute,
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminNodesIndexRoute: AdminNodesIndexRoute,
  AdminOrgsIndexRoute: AdminOrgsIndexRoute,
  AdminSubdomainsIndexRoute: AdminSubdomainsIndexRoute,
  AdminTemplatesIndexRoute: AdminTemplatesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminTemplatesTemplateIdEditRoute: AdminTemplatesTemplateIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
