// Package contract provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package contract

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for DownloadJobState.
const (
	DownloadJobStateCancelled DownloadJobState = "cancelled"
	DownloadJobStateDone      DownloadJobState = "done"
	DownloadJobStateError     DownloadJobState = "error"
	DownloadJobStateRunning   DownloadJobState = "running"
)

// Defines values for FileEntryType.
const (
	FileEntryTypeDir     FileEntryType = "dir"
	FileEntryTypeFile    FileEntryType = "file"
	FileEntryTypeSymlink FileEntryType = "symlink"
)

// Defines values for RedisSetRequestType.
const (
	Hash   RedisSetRequestType = "hash"
	List   RedisSetRequestType = "list"
	Set    RedisSetRequestType = "set"
	String RedisSetRequestType = "string"
	Zset   RedisSetRequestType = "zset"
)

// Defines values for SqlAddColumnRequestEngine.
const (
	SqlAddColumnRequestEngineMysql    SqlAddColumnRequestEngine = "mysql"
	SqlAddColumnRequestEnginePostgres SqlAddColumnRequestEngine = "postgres"
)

// Defines values for SqlAddColumnRequestKey.
const (
	Empty  SqlAddColumnRequestKey = ""
	Index  SqlAddColumnRequestKey = "index"
	Unique SqlAddColumnRequestKey = "unique"
)

// Defines values for SqlAuthEngine.
const (
	SqlAuthEngineMysql    SqlAuthEngine = "mysql"
	SqlAuthEnginePostgres SqlAuthEngine = "postgres"
)

// Defines values for SqlCreateDbRequestEngine.
const (
	SqlCreateDbRequestEngineMysql    SqlCreateDbRequestEngine = "mysql"
	SqlCreateDbRequestEnginePostgres SqlCreateDbRequestEngine = "postgres"
)

// Defines values for SqlCreateUserRequestEngine.
const (
	SqlCreateUserRequestEngineMysql    SqlCreateUserRequestEngine = "mysql"
	SqlCreateUserRequestEnginePostgres SqlCreateUserRequestEngine = "postgres"
)

// Defines values for SqlDbRequestEngine.
const (
	SqlDbRequestEngineMysql    SqlDbRequestEngine = "mysql"
	SqlDbRequestEnginePostgres SqlDbRequestEngine = "postgres"
)

// Defines values for SqlDropColumnRequestEngine.
const (
	SqlDropColumnRequestEngineMysql    SqlDropColumnRequestEngine = "mysql"
	SqlDropColumnRequestEnginePostgres SqlDropColumnRequestEngine = "postgres"
)

// Defines values for SqlDropUserRequestEngine.
const (
	SqlDropUserRequestEngineMysql    SqlDropUserRequestEngine = "mysql"
	SqlDropUserRequestEnginePostgres SqlDropUserRequestEngine = "postgres"
)

// Defines values for SqlTableRequestEngine.
const (
	SqlTableRequestEngineMysql    SqlTableRequestEngine = "mysql"
	SqlTableRequestEnginePostgres SqlTableRequestEngine = "postgres"
)

// Defines values for TrashEntryType.
const (
	TrashEntryTypeDir     TrashEntryType = "dir"
	TrashEntryTypeFile    TrashEntryType = "file"
	TrashEntryTypeSymlink TrashEntryType = "symlink"
)

// ArchiveRequest defines model for ArchiveRequest.
type ArchiveRequest struct {
	Dest   string   `json:"dest"`
	Format string   `json:"format"`
	Paths  []string `json:"paths"`
}

// AttachRequest defines model for AttachRequest.
type AttachRequest struct {
	ServerId string `json:"serverId"`
}

// Backup defines model for Backup.
type Backup struct {
	Archive   string    `json:"archive"`
	CreatedAt time.Time `json:"createdAt"`
	Error     *string   `json:"error,omitempty"`
	Locked    bool      `json:"locked"`
	Name      string    `json:"name"`
	ServerId  string    `json:"serverId"`
	SizeBytes int64     `json:"sizeBytes"`
	Status    string    `json:"status"`
}

// ConfigFile defines model for ConfigFile.
type ConfigFile struct {
	File    string            `json:"file"`
	Parser  string            `json:"parser"`
	Replace map[string]string `json:"replace"`
}

// CreateBackupRequest defines model for CreateBackupRequest.
type CreateBackupRequest struct {
	Name string `json:"name"`
}

// CreateNetworkRequest defines model for CreateNetworkRequest.
type CreateNetworkRequest struct {
	Driver    *string `json:"driver,omitempty"`
	Gateway   *string `json:"gateway,omitempty"`
	Name      string  `json:"name"`
	NetworkId string  `json:"networkId"`
	Subnet    *string `json:"subnet,omitempty"`
}

// CreateServerRequest defines model for CreateServerRequest.
type CreateServerRequest struct {
	ConfigFiles    *[]ConfigFile      `json:"configFiles,omitempty"`
	DiskMb         *int               `json:"diskMb,omitempty"`
	Env            *map[string]string `json:"env,omitempty"`
	Image          string             `json:"image"`
	Install        *InstallSpec       `json:"install,omitempty"`
	MemoryMb       *int               `json:"memoryMb,omitempty"`
	Name           string             `json:"name"`
	NanoCpus       *int64             `json:"nanoCpus,omitempty"`
	PortBinding    *PortBinding       `json:"portBinding,omitempty"`
	ServerId       string             `json:"serverId"`
	StartupCommand *string            `json:"startupCommand,omitempty"`
	StopSignal     *string            `json:"stopSignal,omitempty"`
}

// DeviceRequest defines model for DeviceRequest.
type DeviceRequest struct {
	Device string `json:"device"`
}

// DockerInfo defines model for DockerInfo.
type DockerInfo struct {
	Available     bool    `json:"available"`
	Containers    int     `json:"containers"`
	Error         *string `json:"error,omitempty"`
	Images        int     `json:"images"`
	Running       int     `json:"running"`
	ServerVersion *string `json:"serverVersion,omitempty"`
}

// DownloadJob defines model for DownloadJob.
type DownloadJob struct {
	Done      int64            `json:"done"`
	Error     *string          `json:"error,omitempty"`
	Id        string           `json:"id"`
	Path      string           `json:"path"`
	ServerId  string           `json:"serverId"`
	StartedAt time.Time        `json:"startedAt"`
	State     DownloadJobState `json:"state"`
	Total     int64            `json:"total"`
	UpdatedAt time.Time        `json:"updatedAt"`
	Url       string           `json:"url"`
}

// DownloadJobState defines model for DownloadJob.State.
type DownloadJobState string

// Drive defines model for Drive.
type Drive struct {
	Device       string `json:"device"`
	Filesystem   string `json:"filesystem"`
	IsDataTarget bool   `json:"isDataTarget"`
	Model        string `json:"model"`
	Mountpoint   string `json:"mountpoint"`
	SizeBytes    int64  `json:"sizeBytes"`
	System       bool   `json:"system"`
	UsedBytes    *int64 `json:"usedBytes"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// ExtractRequest defines model for ExtractRequest.
type ExtractRequest struct {
	Dest string `json:"dest"`
	Path string `json:"path"`
}

// FileContent defines model for FileContent.
type FileContent struct {
	Content string `json:"content"`
}

// FileEntry defines model for FileEntry.
type FileEntry struct {
	ModTime time.Time     `json:"modTime"`
	Mode    string        `json:"mode"`
	Name    string        `json:"name"`
	Path    string        `json:"path"`
	Size    int64         `json:"size"`
	Type    FileEntryType `json:"type"`
}

// FileEntryType defines model for FileEntry.Type.
type FileEntryType string

// FirewallRule defines model for FirewallRule.
type FirewallRule struct {
	Port     int    `json:"port"`
	Protocol string `json:"protocol"`
}

// FirewallStatus defines model for FirewallStatus.
type FirewallStatus struct {
	Active  bool           `json:"active"`
	Backend string         `json:"backend"`
	Rules   []FirewallRule `json:"rules"`
}

// FormatDriveRequest defines model for FormatDriveRequest.
type FormatDriveRequest struct {
	Device     string `json:"device"`
	Filesystem string `json:"filesystem"`
	Mountpoint string `json:"mountpoint"`
}

// HostInfo defines model for HostInfo.
type HostInfo struct {
	Arch            string `json:"arch"`
	CpuCount        int    `json:"cpuCount"`
	CpuModel        string `json:"cpuModel"`
	Hostname        string `json:"hostname"`
	Kernel          string `json:"kernel"`
	MemTotalBytes   int64  `json:"memTotalBytes"`
	Os              string `json:"os"`
	Platform        string `json:"platform"`
	PlatformVersion string `json:"platformVersion"`
	UptimeSeconds   int64  `json:"uptimeSeconds"`
}

// InstallSpec defines model for InstallSpec.
type InstallSpec struct {
	Entrypoint *string            `json:"entrypoint,omitempty"`
	Env        *map[string]string `json:"env,omitempty"`
	Image      string             `json:"image"`
	Script     string             `json:"script"`
}

// JobAccepted defines model for JobAccepted.
type JobAccepted struct {
	JobId string `json:"jobId"`
}

// LockBackupRequest defines model for LockBackupRequest.
type LockBackupRequest struct {
	Locked bool `json:"locked"`
}

// MongoAuth defines model for MongoAuth.
type MongoAuth struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// MongoCollection defines model for MongoCollection.
type MongoCollection struct {
	Documents int64  `json:"documents"`
	Indexes   int64  `json:"indexes"`
	Name      string `json:"name"`
	SizeBytes int64  `json:"sizeBytes"`
}

// MongoCollectionRequest defines model for MongoCollectionRequest.
type MongoCollectionRequest struct {
	Collection string `json:"collection"`
	Db         string `json:"db"`
	Password   string `json:"password"`
	Username   string `json:"username"`
}

// MongoDatabase defines model for MongoDatabase.
type MongoDatabase struct {
	Name      string `json:"name"`
	SizeBytes int64  `json:"sizeBytes"`
}

// MongoDbRequest defines model for MongoDbRequest.
type MongoDbRequest struct {
	Db       string `json:"db"`
	Password string `json:"password"`
	Username string `json:"username"`
}

// MongoDeleteRequest defines model for MongoDeleteRequest.
type MongoDeleteRequest struct {
	Collection string `json:"collection"`
	Db         string `json:"db"`
	Id         string `json:"id"`
	Password   string `json:"password"`
	Username   string `json:"username"`
}

// MongoDocument defines model for MongoDocument.
type MongoDocument struct {
	Id   string `json:"id"`
	Json string `json:"json"`
}

// MongoDocumentPage defines model for MongoDocumentPage.
type MongoDocumentPage struct {
	Documents []MongoDocument `json:"documents"`
	Total     int64           `json:"total"`
}

// MongoFindRequest defines model for MongoFindRequest.
type MongoFindRequest struct {
	Collection string `json:"collection"`
	Db         string `json:"db"`
	Limit      *int64 `json:"limit,omitempty"`
	Password   string `json:"password"`
	Skip       *int64 `json:"skip,omitempty"`
	Username   string `json:"username"`
}

// MongoInsertRequest defines model for MongoInsertRequest.
type MongoInsertRequest struct {
	Collection string `json:"collection"`
	Db         string `json:"db"`
	Doc        string `json:"doc"`
	Password   string `json:"password"`
	Username   string `json:"username"`
}

// MountDriveRequest defines model for MountDriveRequest.
type MountDriveRequest struct {
	Device     string `json:"device"`
	Mountpoint string `json:"mountpoint"`
}

// Network defines model for Network.
type Network struct {
	Driver    string  `json:"driver"`
	Gateway   *string `json:"gateway,omitempty"`
	Id        string  `json:"id"`
	Name      string  `json:"name"`
	NetworkId string  `json:"networkId"`
	Subnet    *string `json:"subnet,omitempty"`
}

// PathRequest defines model for PathRequest.
type PathRequest struct {
	Path string `json:"path"`
}

// PortBinding defines model for PortBinding.
type PortBinding struct {
	ContainerPort int     `json:"containerPort"`
	HostIp        string  `json:"hostIp"`
	HostPort      int     `json:"hostPort"`
	Protocol      *string `json:"protocol,omitempty"`
}

// PruneResult defines model for PruneResult.
type PruneResult struct {
	ImagesDeleted       int   `json:"imagesDeleted"`
	SpaceReclaimedBytes int64 `json:"spaceReclaimedBytes"`
}

// PurgeResult defines model for PurgeResult.
type PurgeResult struct {
	Purged int `json:"purged"`
}

// RedisAuth defines model for RedisAuth.
type RedisAuth struct {
	Db       int    `json:"db"`
	Password string `json:"password"`
}

// RedisDBKeyspace defines model for RedisDBKeyspace.
type RedisDBKeyspace struct {
	Db      int   `json:"db"`
	Expires int64 `json:"expires"`
	Keys    int64 `json:"keys"`
}

// RedisField defines model for RedisField.
type RedisField struct {
	Field string `json:"field"`
	Value string `json:"value"`
}

// RedisKeyDetail defines model for RedisKeyDetail.
type RedisKeyDetail struct {
	Entries    *[]RedisStreamEntry `json:"entries,omitempty"`
	Fields     *[]RedisField       `json:"fields,omitempty"`
	Items      *[]string           `json:"items,omitempty"`
	Key        string              `json:"key"`
	Length     int64               `json:"length"`
	Members    *[]RedisScoreMember `json:"members,omitempty"`
	SizeBytes  int64               `json:"sizeBytes"`
	String     *string             `json:"string,omitempty"`
	Truncated  bool                `json:"truncated"`
	TtlSeconds int64               `json:"ttlSeconds"`
	Type       string              `json:"type"`
}

// RedisKeyList defines model for RedisKeyList.
type RedisKeyList struct {
	Cursor string            `json:"cursor"`
	Keys   []RedisKeySummary `json:"keys"`
}

// RedisKeyRequest defines model for RedisKeyRequest.
type RedisKeyRequest struct {
	Db       int    `json:"db"`
	Key      string `json:"key"`
	Password string `json:"password"`
}

// RedisKeySummary defines model for RedisKeySummary.
type RedisKeySummary struct {
	Key        string `json:"key"`
	Length     int64  `json:"length"`
	SizeBytes  int64  `json:"sizeBytes"`
	TtlSeconds int64  `json:"ttlSeconds"`
	Type       string `json:"type"`
}

// RedisKeysRequest defines model for RedisKeysRequest.
type RedisKeysRequest struct {
	Count    *int64  `json:"count,omitempty"`
	Cursor   *string `json:"cursor,omitempty"`
	Db       int     `json:"db"`
	Password string  `json:"password"`
	Pattern  *string `json:"pattern,omitempty"`
}

// RedisOverview defines model for RedisOverview.
type RedisOverview struct {
	ConnectedClients int64             `json:"connectedClients"`
	Databases        []RedisDBKeyspace `json:"databases"`
	KeyspaceHits     int64             `json:"keyspaceHits"`
	KeyspaceMisses   int64             `json:"keyspaceMisses"`
	MaxMemoryBytes   int64             `json:"maxMemoryBytes"`
	Mode             string            `json:"mode"`
	PeakMemoryBytes  int64             `json:"peakMemoryBytes"`
	TotalCommands    int64             `json:"totalCommands"`
	UptimeSeconds    int64             `json:"uptimeSeconds"`
	UsedMemoryBytes  int64             `json:"usedMemoryBytes"`
	Version          string            `json:"version"`
}

// RedisRenameRequest defines model for RedisRenameRequest.
type RedisRenameRequest struct {
	Db       int    `json:"db"`
	Key      string `json:"key"`
	NewKey   string `json:"newKey"`
	Password string `json:"password"`
}

// RedisScoreMember defines model for RedisScoreMember.
type RedisScoreMember struct {
	Member string  `json:"member"`
	Score  float64 `json:"score"`
}

// RedisSetBody defines model for RedisSetBody.
type RedisSetBody struct {
	Db       int             `json:"db"`
	Password string          `json:"password"`
	Set      RedisSetRequest `json:"set"`
}

// RedisSetRequest defines model for RedisSetRequest.
type RedisSetRequest struct {
	Fields     *[]RedisField       `json:"fields,omitempty"`
	Items      *[]string           `json:"items,omitempty"`
	Key        string              `json:"key"`
	Members    *[]RedisScoreMember `json:"members,omitempty"`
	String     *string             `json:"string,omitempty"`
	TtlSeconds int64               `json:"ttlSeconds"`
	Type       RedisSetRequestType `json:"type"`
}

// RedisSetRequestType defines model for RedisSetRequest.Type.
type RedisSetRequestType string

// RedisStreamEntry defines model for RedisStreamEntry.
type RedisStreamEntry struct {
	Fields []RedisField `json:"fields"`
	Id     string       `json:"id"`
}

// RedisTtlRequest defines model for RedisTtlRequest.
type RedisTtlRequest struct {
	Db         int    `json:"db"`
	Key        string `json:"key"`
	Password   string `json:"password"`
	TtlSeconds int64  `json:"ttlSeconds"`
}

// RenameRequest defines model for RenameRequest.
type RenameRequest struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// RestoreBackupRequest defines model for RestoreBackupRequest.
type RestoreBackupRequest struct {
	Archive string `json:"archive"`
}

// Schedule defines model for Schedule.
type Schedule struct {
	Cron       string         `json:"cron"`
	Enabled    bool           `json:"enabled"`
	Id         string         `json:"id"`
	LastError  *string        `json:"lastError,omitempty"`
	LastRunAt  *time.Time     `json:"lastRunAt,omitempty"`
	LastStatus *string        `json:"lastStatus,omitempty"`
	Name       string         `json:"name"`
	ServerId   string         `json:"serverId"`
	Steps      []ScheduleStep `json:"steps"`
}

// ScheduleStep defines model for ScheduleStep.
type ScheduleStep struct {
	Command *string `json:"command,omitempty"`
	Power   *string `json:"power,omitempty"`
	Seconds *int    `json:"seconds,omitempty"`
	Type    string  `json:"type"`
}

// Server defines model for Server.
type Server struct {
	ContainerId string  `json:"containerId"`
	Error       *string `json:"error,omitempty"`
	Image       string  `json:"image"`
	Name        string  `json:"name"`
	ServerId    string  `json:"serverId"`
	State       string  `json:"state"`
	Status      string  `json:"status"`
}

// ServerCommandRequest defines model for ServerCommandRequest.
type ServerCommandRequest struct {
	Command string `json:"command"`
}

// SftpMintResponse defines model for SftpMintResponse.
type SftpMintResponse struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Password  string    `json:"password"`
	Port      int       `json:"port"`
	Username  string    `json:"username"`
}

// SftpStatusResponse defines model for SftpStatusResponse.
type SftpStatusResponse struct {
	Active    bool       `json:"active"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
	Port      int        `json:"port"`
	Username  *string    `json:"username,omitempty"`
}

// SqlAddColumnRequest defines model for SqlAddColumnRequest.
type SqlAddColumnRequest struct {
	Db       string                    `json:"db"`
	Engine   SqlAddColumnRequestEngine `json:"engine"`
	Key      *SqlAddColumnRequestKey   `json:"key,omitempty"`
	Name     string                    `json:"name"`
	Nullable *bool                     `json:"nullable,omitempty"`
	Password string                    `json:"password"`
	Table    string                    `json:"table"`
	Type     string                    `json:"type"`
	Username string                    `json:"username"`
}

// SqlAddColumnRequestEngine defines model for SqlAddColumnRequest.Engine.
type SqlAddColumnRequestEngine string

// SqlAddColumnRequestKey defines model for SqlAddColumnRequest.Key.
type SqlAddColumnRequestKey string

// SqlAuth defines model for SqlAuth.
type SqlAuth struct {
	Engine   SqlAuthEngine `json:"engine"`
	Password string        `json:"password"`
	Username string        `json:"username"`
}

// SqlAuthEngine defines model for SqlAuth.Engine.
type SqlAuthEngine string

// SqlColumn defines model for SqlColumn.
type SqlColumn struct {
	Default  *string `json:"default"`
	Key      string  `json:"key"`
	Name     string  `json:"name"`
	Nullable bool    `json:"nullable"`
	Type     string  `json:"type"`
}

// SqlCreateDbRequest defines model for SqlCreateDbRequest.
type SqlCreateDbRequest struct {
	Charset  *string                  `json:"charset,omitempty"`
	Db       string                   `json:"db"`
	Engine   SqlCreateDbRequestEngine `json:"engine"`
	Password string                   `json:"password"`
	Username string                   `json:"username"`
}

// SqlCreateDbRequestEngine defines model for SqlCreateDbRequest.Engine.
type SqlCreateDbRequestEngine string

// SqlCreateUserRequest defines model for SqlCreateUserRequest.
type SqlCreateUserRequest struct {
	Access      *string                    `json:"access,omitempty"`
	Engine      SqlCreateUserRequestEngine `json:"engine"`
	Host        *string                    `json:"host,omitempty"`
	Name        string                     `json:"name"`
	NewPassword *string                    `json:"newPassword,omitempty"`
	Password    string                     `json:"password"`
	Username    string                     `json:"username"`
}

// SqlCreateUserRequestEngine defines model for SqlCreateUserRequest.Engine.
type SqlCreateUserRequestEngine string

// SqlDatabase defines model for SqlDatabase.
type SqlDatabase struct {
	Charset   string `json:"charset"`
	Name      string `json:"name"`
	SizeBytes int64  `json:"sizeBytes"`
	Tables    int64  `json:"tables"`
}

// SqlDbRequest defines model for SqlDbRequest.
type SqlDbRequest struct {
	Db       string             `json:"db"`
	Engine   SqlDbRequestEngine `json:"engine"`
	Password string             `json:"password"`
	Username string             `json:"username"`
}

// SqlDbRequestEngine defines model for SqlDbRequest.Engine.
type SqlDbRequestEngine string

// SqlDropColumnRequest defines model for SqlDropColumnRequest.
type SqlDropColumnRequest struct {
	Column   string                     `json:"column"`
	Db       string                     `json:"db"`
	Engine   SqlDropColumnRequestEngine `json:"engine"`
	Password string                     `json:"password"`
	Table    string                     `json:"table"`
	Username string                     `json:"username"`
}

// SqlDropColumnRequestEngine defines model for SqlDropColumnRequest.Engine.
type SqlDropColumnRequestEngine string

// SqlDropUserRequest defines model for SqlDropUserRequest.
type SqlDropUserRequest struct {
	Engine   SqlDropUserRequestEngine `json:"engine"`
	Host     *string                  `json:"host,omitempty"`
	Name     string                   `json:"name"`
	Password string                   `json:"password"`
	Username string                   `json:"username"`
}

// SqlDropUserRequestEngine defines model for SqlDropUserRequest.Engine.
type SqlDropUserRequestEngine string

// SqlTable defines model for SqlTable.
type SqlTable struct {
	Columns   int64  `json:"columns"`
	Name      string `json:"name"`
	Rows      int64  `json:"rows"`
	SizeBytes int64  `json:"sizeBytes"`
}

// SqlTableRequest defines model for SqlTableRequest.
type SqlTableRequest struct {
	Db       string                `json:"db"`
	Engine   SqlTableRequestEngine `json:"engine"`
	Password string                `json:"password"`
	Table    string                `json:"table"`
	Username string                `json:"username"`
}

// SqlTableRequestEngine defines model for SqlTableRequest.Engine.
type SqlTableRequestEngine string

// SqlUser defines model for SqlUser.
type SqlUser struct {
	Grants    []string `json:"grants"`
	Host      string   `json:"host"`
	Name      string   `json:"name"`
	Superuser bool     `json:"superuser"`
}

// Stats defines model for Stats.
type Stats struct {
	CpuPct         float64 `json:"cpuPct"`
	DiskTotalBytes int64   `json:"diskTotalBytes"`
	DiskUsedBytes  int64   `json:"diskUsedBytes"`
	Load1          float64 `json:"load1"`
	Load15         float64 `json:"load15"`
	Load5          float64 `json:"load5"`
	MemTotalBytes  int64   `json:"memTotalBytes"`
	MemUsedBytes   int64   `json:"memUsedBytes"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Status string `json:"status"`
}

// System defines model for System.
type System struct {
	DaemonStartedAt time.Time              `json:"daemonStartedAt"`
	DaemonVersion   string                 `json:"daemonVersion"`
	Docker          DockerInfo             `json:"docker"`
	NodeId          string                 `json:"nodeId"`
	System          map[string]interface{} `json:"system"`
	UptimeSeconds   int64                  `json:"uptimeSeconds"`
}

// TrashEntry defines model for TrashEntry.
type TrashEntry struct {
	DeletedAt    time.Time      `json:"deletedAt"`
	Id           string         `json:"id"`
	Name         string         `json:"name"`
	OriginalPath string         `json:"originalPath"`
	Size         int64          `json:"size"`
	Type         TrashEntryType `json:"type"`
}

// TrashEntryType defines model for TrashEntry.Type.
type TrashEntryType string

// TrashIdRequest defines model for TrashIdRequest.
type TrashIdRequest struct {
	Id string `json:"id"`
}

// TrashPurgeRequest defines model for TrashPurgeRequest.
type TrashPurgeRequest struct {
	MaxAgeSeconds int64 `json:"maxAgeSeconds"`
}

// UpdateDaemonRequest defines model for UpdateDaemonRequest.
type UpdateDaemonRequest struct {
	Sha256 string `json:"sha256"`
	Url    string `json:"url"`
}

// UrlDownloadRequest defines model for UrlDownloadRequest.
type UrlDownloadRequest struct {
	Path string `json:"path"`
	Url  string `json:"url"`
}

// WriteFileRequest defines model for WriteFileRequest.
type WriteFileRequest struct {
	Content string `json:"content"`
	Path    string `json:"path"`
}

// Archive defines model for Archive.
type Archive = string

// JobId defines model for JobId.
type JobId = string

// NetworkId defines model for NetworkId.
type NetworkId = string

// PathQuery defines model for PathQuery.
type PathQuery = string

// ScheduleId defines model for ScheduleId.
type ScheduleId = string

// ServerId defines model for ServerId.
type ServerId = string

// BadGateway defines model for BadGateway.
type BadGateway = Error

// Conflict defines model for Conflict.
type Conflict = Error

// Forbidden defines model for Forbidden.
type Forbidden = Error

// NotFound defines model for NotFound.
type NotFound = Error

// NotImplemented defines model for NotImplemented.
type NotImplemented = Error

// DownloadFileParams defines parameters for DownloadFile.
type DownloadFileParams struct {
	Path PathQuery `form:"path" json:"path"`
}

// ListFilesParams defines parameters for ListFiles.
type ListFilesParams struct {
	Path PathQuery `form:"path" json:"path"`
}

// ReadFileParams defines parameters for ReadFile.
type ReadFileParams struct {
	Path PathQuery `form:"path" json:"path"`
}

// UploadFileParams defines parameters for UploadFile.
type UploadFileParams struct {
	Path PathQuery `form:"path" json:"path"`
}

// SetDataTargetJSONRequestBody defines body for SetDataTarget for application/json ContentType.
type SetDataTargetJSONRequestBody = DeviceRequest

// FormatDriveJSONRequestBody defines body for FormatDrive for application/json ContentType.
type FormatDriveJSONRequestBody = FormatDriveRequest

// MountDriveJSONRequestBody defines body for MountDrive for application/json ContentType.
type MountDriveJSONRequestBody = MountDriveRequest

// UnmountDriveJSONRequestBody defines body for UnmountDrive for application/json ContentType.
type UnmountDriveJSONRequestBody = DeviceRequest

// CloseFirewallPortJSONRequestBody defines body for CloseFirewallPort for application/json ContentType.
type CloseFirewallPortJSONRequestBody = FirewallRule

// OpenFirewallPortJSONRequestBody defines body for OpenFirewallPort for application/json ContentType.
type OpenFirewallPortJSONRequestBody = FirewallRule

// CreateNetworkJSONRequestBody defines body for CreateNetwork for application/json ContentType.
type CreateNetworkJSONRequestBody = CreateNetworkRequest

// AttachNetworkJSONRequestBody defines body for AttachNetwork for application/json ContentType.
type AttachNetworkJSONRequestBody = AttachRequest

// DetachNetworkJSONRequestBody defines body for DetachNetwork for application/json ContentType.
type DetachNetworkJSONRequestBody = AttachRequest

// UpsertScheduleJSONRequestBody defines body for UpsertSchedule for application/json ContentType.
type UpsertScheduleJSONRequestBody = Schedule

// CreateServerJSONRequestBody defines body for CreateServer for application/json ContentType.
type CreateServerJSONRequestBody = CreateServerRequest

// CreateBackupJSONRequestBody defines body for CreateBackup for application/json ContentType.
type CreateBackupJSONRequestBody = CreateBackupRequest

// RestoreBackupJSONRequestBody defines body for RestoreBackup for application/json ContentType.
type RestoreBackupJSONRequestBody = RestoreBackupRequest

// LockBackupJSONRequestBody defines body for LockBackup for application/json ContentType.
type LockBackupJSONRequestBody = LockBackupRequest

// SendServerCommandJSONRequestBody defines body for SendServerCommand for application/json ContentType.
type SendServerCommandJSONRequestBody = ServerCommandRequest

// ArchiveFilesJSONRequestBody defines body for ArchiveFiles for application/json ContentType.
type ArchiveFilesJSONRequestBody = ArchiveRequest

// DeleteFileJSONRequestBody defines body for DeleteFile for application/json ContentType.
type DeleteFileJSONRequestBody = PathRequest

// ExtractFileJSONRequestBody defines body for ExtractFile for application/json ContentType.
type ExtractFileJSONRequestBody = ExtractRequest

// MkdirJSONRequestBody defines body for Mkdir for application/json ContentType.
type MkdirJSONRequestBody = PathRequest

// RenameFileJSONRequestBody defines body for RenameFile for application/json ContentType.
type RenameFileJSONRequestBody = RenameRequest

// DeleteTrashJSONRequestBody defines body for DeleteTrash for application/json ContentType.
type DeleteTrashJSONRequestBody = TrashIdRequest

// PurgeTrashJSONRequestBody defines body for PurgeTrash for application/json ContentType.
type PurgeTrashJSONRequestBody = TrashPurgeRequest

// RestoreTrashJSONRequestBody defines body for RestoreTrash for application/json ContentType.
type RestoreTrashJSONRequestBody = TrashIdRequest

// StartUrlDownloadJSONRequestBody defines body for StartUrlDownload for application/json ContentType.
type StartUrlDownloadJSONRequestBody = UrlDownloadRequest

// WriteFileJSONRequestBody defines body for WriteFile for application/json ContentType.
type WriteFileJSONRequestBody = WriteFileRequest

// MongoCollectionsJSONRequestBody defines body for MongoCollections for application/json ContentType.
type MongoCollectionsJSONRequestBody = MongoDbRequest

// MongoCreateCollectionJSONRequestBody defines body for MongoCreateCollection for application/json ContentType.
type MongoCreateCollectionJSONRequestBody = MongoCollectionRequest

// MongoDatabasesJSONRequestBody defines body for MongoDatabases for application/json ContentType.
type MongoDatabasesJSONRequestBody = MongoAuth

// MongoDeleteJSONRequestBody defines body for MongoDelete for application/json ContentType.
type MongoDeleteJSONRequestBody = MongoDeleteRequest

// MongoDocumentsJSONRequestBody defines body for MongoDocuments for application/json ContentType.
type MongoDocumentsJSONRequestBody = MongoFindRequest

// MongoDropCollectionJSONRequestBody defines body for MongoDropCollection for application/json ContentType.
type MongoDropCollectionJSONRequestBody = MongoCollectionRequest

// MongoDropDatabaseJSONRequestBody defines body for MongoDropDatabase for application/json ContentType.
type MongoDropDatabaseJSONRequestBody = MongoDbRequest

// MongoInsertJSONRequestBody defines body for MongoInsert for application/json ContentType.
type MongoInsertJSONRequestBody = MongoInsertRequest

// RedisDeleteJSONRequestBody defines body for RedisDelete for application/json ContentType.
type RedisDeleteJSONRequestBody = RedisKeyRequest

// RedisFlushJSONRequestBody defines body for RedisFlush for application/json ContentType.
type RedisFlushJSONRequestBody = RedisAuth

// RedisKeyJSONRequestBody defines body for RedisKey for application/json ContentType.
type RedisKeyJSONRequestBody = RedisKeyRequest

// RedisKeysJSONRequestBody defines body for RedisKeys for application/json ContentType.
type RedisKeysJSONRequestBody = RedisKeysRequest

// RedisOverviewJSONRequestBody defines body for RedisOverview for application/json ContentType.
type RedisOverviewJSONRequestBody = RedisAuth

// RedisRenameJSONRequestBody defines body for RedisRename for application/json ContentType.
type RedisRenameJSONRequestBody = RedisRenameRequest

// RedisSetJSONRequestBody defines body for RedisSet for application/json ContentType.
type RedisSetJSONRequestBody = RedisSetBody

// RedisTtlJSONRequestBody defines body for RedisTtl for application/json ContentType.
type RedisTtlJSONRequestBody = RedisTtlRequest

// SqlAddColumnJSONRequestBody defines body for SqlAddColumn for application/json ContentType.
type SqlAddColumnJSONRequestBody = SqlAddColumnRequest

// SqlColumnsJSONRequestBody defines body for SqlColumns for application/json ContentType.
type SqlColumnsJSONRequestBody = SqlTableRequest

// SqlCreateDatabaseJSONRequestBody defines body for SqlCreateDatabase for application/json ContentType.
type SqlCreateDatabaseJSONRequestBody = SqlCreateDbRequest

// SqlCreateTableJSONRequestBody defines body for SqlCreateTable for application/json ContentType.
type SqlCreateTableJSONRequestBody = SqlTableRequest

// SqlCreateUserJSONRequestBody defines body for SqlCreateUser for application/json ContentType.
type SqlCreateUserJSONRequestBody = SqlCreateUserRequest

// SqlDatabasesJSONRequestBody defines body for SqlDatabases for application/json ContentType.
type SqlDatabasesJSONRequestBody = SqlAuth

// SqlDropColumnJSONRequestBody defines body for SqlDropColumn for application/json ContentType.
type SqlDropColumnJSONRequestBody = SqlDropColumnRequest

// SqlDropDatabaseJSONRequestBody defines body for SqlDropDatabase for application/json ContentType.
type SqlDropDatabaseJSONRequestBody = SqlDbRequest

// SqlDropTableJSONRequestBody defines body for SqlDropTable for application/json ContentType.
type SqlDropTableJSONRequestBody = SqlTableRequest

// SqlDropUserJSONRequestBody defines body for SqlDropUser for application/json ContentType.
type SqlDropUserJSONRequestBody = SqlDropUserRequest

// SqlTablesJSONRequestBody defines body for SqlTables for application/json ContentType.
type SqlTablesJSONRequestBody = SqlDbRequest

// SqlTruncateTableJSONRequestBody defines body for SqlTruncateTable for application/json ContentType.
type SqlTruncateTableJSONRequestBody = SqlTableRequest

// SqlUsersJSONRequestBody defines body for SqlUsers for application/json ContentType.
type SqlUsersJSONRequestBody = SqlAuth

// UpdateDaemonJSONRequestBody defines body for UpdateDaemon for application/json ContentType.
type UpdateDaemonJSONRequestBody = UpdateDaemonRequest
