/**
 * Drizzle schema barrel — one file per concern, re-exported here. This is what
 * the db client and drizzle-kit read.
 *
 * `auth.ts` is generated by Better Auth's CLI from `src/server/auth`: the
 * identity + tenancy tables (user, session, account, verification, organization,
 * member, invitation). Regenerate after changing the auth config with
 * `pnpm --filter @cookiepanel/panel auth:generate`, then `db:generate`.
 *
 * App-owned tables (nodes, templates + images + variables, port allocations,
 * ssh keys, activity log) land here as features wire up; each carries
 * `organizationId` for the repository-layer org-scoping backstop (`security.md`).
 */
export * from "./auth";
