// Placeholder data for the UI-first phase. One source of truth so pages agree —
// the same nodes back the servers + drives stubs, the same template labels recur,
// so the fleet reads as one believable org. Replace these when the data layer
// lands (nodes/networks/allocations/firewall already have). Every row here is
// client-safe: no secrets, and never a raw Docker image string (templates expose
// only a friendly label).
//
// Ids are UUIDs, matching the real schema (the panel mints UUID primary keys).

import type { DriveRow } from "@/lib/domain/nodes";
import type { Template } from "@/lib/domain/templates";

const GiB = 1024 ** 3;
const TiB = 1024 ** 4;

// — Nodes ————————————————————————————————————————————————————————————————————

// Node UUIDs, still referenced by the servers + drives stubs (by nodeId). The
// nodes/networks/allocations/firewall stub arrays were retired once those
// features moved onto the real data layer.
const NODE_ID = {
	atlas: "a7f3c1d2-4e5b-4a6c-9d8e-1f2a3b4c5d6e",
	valhalla: "b8e4d2c3-5f6a-4b7d-8e9f-2a3b4c5d6e7f",
	orion: "c9f5e3d4-6a7b-4c8e-9f0a-3b4c5d6e7f80",
	helios: "d0a6f4e5-7b8c-4d9f-8a1b-4c5d6e7f8091",
	nova: "e1b7a5f6-8c9d-4e0a-9b2c-5d6e7f8091a2",
	titan: "f2c8b6a7-9d0e-4f1b-8c3d-6e7f8091a2b3",
} as const;

// — Templates —————————————————————————————————————————————————————————————————
// Full authoring records (the panel's "eggs"). Domain types + helpers live in
// lib/domain/templates.ts. These now seed the *official* (platform-owned)
// templates in the database — see server/db/seed.ts — so the catalog renders the
// same library the UI-first phase showed. Image strings appear here because the
// *author* sees them in the editor; they're never surfaced on the catalog, the
// detail page, or a server.

export const TEMPLATES: Template[] = [
	{
		id: "c4d5e6f7-1a2b-4c3d-8e4f-5a6b7c8d9e0f",
		name: "Minecraft: Java Edition",
		slug: "minecraft-java-edition",
		iconUrl: null,
		summary: "Vanilla Java server with auto EULA and tuned JVM flags.",
		description:
			"The official Mojang Java server, ready to play. Picks sane JVM flags for the memory you give it, accepts the EULA on first start, and exposes the settings most groups change: difficulty, gamemode, and the message of the day.",
		category: "Minecraft",
		official: true,
		origin: "official",
		status: "published",
		version: 7,
		serverCount: 3,
		updatedAt: "May 28, 2026",
		parentName: null,
		images: [
			{
				id: "img-mc-java21",
				label: "Java 21",
				image: "ghcr.io/pterodactyl/yolks:java_21",
				isDefault: true,
			},
			{
				id: "img-mc-java17",
				label: "Java 17",
				image: "ghcr.io/pterodactyl/yolks:java_17",
				isDefault: false,
			},
		],
		variables: [
			{
				id: "var-mc-version",
				name: "Server version",
				description: "Which Minecraft version to download.",
				envVariable: "MINECRAFT_VERSION",
				defaultValue: "latest",
				type: "text",
				required: true,
				options: [],
				access: "editable",
			},
			{
				id: "var-mc-difficulty",
				name: "Difficulty",
				description: "World difficulty.",
				envVariable: "DIFFICULTY",
				defaultValue: "normal",
				type: "select",
				required: true,
				options: ["peaceful", "easy", "normal", "hard"],
				access: "editable",
			},
			{
				id: "var-mc-motd",
				name: "Message of the day",
				description: "Shown in the server list.",
				envVariable: "SERVER_MOTD",
				defaultValue: "A CookiePanel server",
				type: "text",
				required: false,
				options: [],
				access: "editable",
			},
			{
				id: "var-mc-jar",
				name: "Server jar",
				description: "Internal: the downloaded jar filename.",
				envVariable: "SERVER_JARFILE",
				defaultValue: "server.jar",
				type: "text",
				required: true,
				options: [],
				access: "hidden",
			},
		],
		startupCommand:
			"java -Xms128M -Xmx{{SERVER_MEMORY}}M -jar {{SERVER_JARFILE}} nogui",
		stopType: "command",
		stopValue: "stop",
		doneMarkers: [{ kind: "regex", pattern: '\\)! For help, type "help"' }],
		installScript:
			'#!/bin/bash\n# Download the requested Minecraft server jar into /mnt/server.\napt-get update && apt-get install -y curl jq\ncd /mnt/server\necho "Fetching Minecraft server {{MINECRAFT_VERSION}}..."\ncurl -sSL -o {{SERVER_JARFILE}} https://launcher.example/minecraft/{{MINECRAFT_VERSION}}/server.jar\necho "eula=true" > eula.txt\n',
		installContainerImage: "ghcr.io/pterodactyl/installers:debian",
		installEntrypoint: "bash",
		configFiles: [
			{
				file: "server.properties",
				parser: "properties",
				replace: {
					"server-port": "{{SERVER_PORT}}",
					difficulty: "{{DIFFICULTY}}",
					motd: "{{SERVER_MOTD}}",
				},
			},
		],
		features: [{ key: "minecraft:eula" }, { key: "minecraft:bukkit-plugins" }],
	},
	{
		id: "d5e6f7a8-2b3c-4d4e-9f5a-6b7c8d9e0f1a",
		name: "Valheim Dedicated",
		slug: "valheim-dedicated",
		iconUrl: null,
		summary: "Dedicated Valheim world with crossplay and world backups.",
		description:
			"A dedicated Valheim world over SteamCMD. Crossplay is on by default; set a world name and a join password and you're ready.",
		category: "Survival",
		official: true,
		origin: "official",
		status: "published",
		version: 3,
		serverCount: 1,
		updatedAt: "May 12, 2026",
		parentName: null,
		images: [
			{
				id: "img-valheim",
				label: "SteamCMD (Debian)",
				image: "ghcr.io/pterodactyl/yolks:steamcmd_debian",
				isDefault: true,
			},
		],
		variables: [
			{
				id: "var-vh-world",
				name: "World name",
				description: "The save the server loads.",
				envVariable: "WORLD_NAME",
				defaultValue: "Midgard",
				type: "text",
				required: true,
				options: [],
				access: "editable",
			},
			{
				id: "var-vh-password",
				name: "Join password",
				description: "Required to connect (min 5 characters).",
				envVariable: "SERVER_PASSWORD",
				defaultValue: null,
				type: "text",
				required: true,
				options: [],
				access: "secret",
			},
			{
				id: "var-vh-crossplay",
				name: "Crossplay",
				description: "Allow players from all platforms.",
				envVariable: "CROSSPLAY",
				defaultValue: "true",
				type: "toggle",
				required: false,
				options: [],
				access: "editable",
			},
		],
		startupCommand:
			"./valheim_server.x86_64 -name {{WORLD_NAME}} -world {{WORLD_NAME}} -password {{SERVER_PASSWORD}}",
		stopType: "signal",
		stopValue: "SIGINT",
		doneMarkers: [{ kind: "string", value: "Game server connected" }],
		installScript:
			"#!/bin/bash\n# Install the Valheim dedicated server via SteamCMD.\nsteamcmd +force_install_dir /mnt/server +login anonymous +app_update 896660 validate +quit\n",
		installContainerImage: "ghcr.io/pterodactyl/installers:debian",
		installEntrypoint: "bash",
		configFiles: [],
		features: [],
	},
	{
		id: "e6f7a8b9-3c4d-4e5f-8a6b-7c8d9e0f1a2b",
		name: "Palworld",
		slug: "palworld",
		iconUrl: null,
		summary: "Palworld dedicated server with configurable rates and caps.",
		description:
			"A Palworld dedicated server. Tune the capture and breeding rates and the player cap; everything else uses Pocketpair's defaults.",
		category: "Survival",
		official: true,
		origin: "official",
		status: "published",
		version: 2,
		serverCount: 1,
		updatedAt: "Apr 30, 2026",
		parentName: null,
		images: [
			{
				id: "img-palworld",
				label: "SteamCMD (Ubuntu)",
				image: "ghcr.io/pterodactyl/yolks:steamcmd_ubuntu",
				isDefault: true,
			},
		],
		variables: [
			{
				id: "var-pw-name",
				name: "Server name",
				description: "Shown in the community server browser.",
				envVariable: "SERVER_NAME",
				defaultValue: "A Palworld Server",
				type: "text",
				required: true,
				options: [],
				access: "editable",
			},
			{
				id: "var-pw-players",
				name: "Max players",
				description: "Up to 32.",
				envVariable: "MAX_PLAYERS",
				defaultValue: "16",
				type: "number",
				required: true,
				options: [],
				access: "editable",
			},
			{
				id: "var-pw-admin",
				name: "Admin password",
				description: "Grants in-game admin commands.",
				envVariable: "ADMIN_PASSWORD",
				defaultValue: null,
				type: "text",
				required: false,
				options: [],
				access: "secret",
			},
		],
		startupCommand:
			'./PalServer.sh -players={{MAX_PLAYERS}} -servername="{{SERVER_NAME}}"',
		stopType: "signal",
		stopValue: "SIGINT",
		doneMarkers: [{ kind: "string", value: "Setting breakpad minidump" }],
		installScript:
			"#!/bin/bash\nsteamcmd +force_install_dir /mnt/server +login anonymous +app_update 2394010 validate +quit\n",
		installContainerImage: "ghcr.io/pterodactyl/installers:debian",
		installEntrypoint: "bash",
		configFiles: [],
		features: [{ key: "steam:gslt" }],
	},
	{
		id: "f7a8b9c0-4d5e-4f6a-9b7c-8d9e0f1a2b3c",
		name: "Factorio Headless",
		slug: "factorio-headless",
		iconUrl: null,
		summary: "Headless Factorio with mod-portal sync and autosave rotation.",
		description:
			"A headless Factorio server with rotating autosaves. Point it at a mod-portal token to keep mods in sync across restarts.",
		category: "Sandbox",
		official: true,
		origin: "official",
		status: "published",
		version: 6,
		serverCount: 0,
		updatedAt: "May 20, 2026",
		parentName: null,
		images: [
			{
				id: "img-factorio",
				label: "Factorio (latest)",
				image: "factoriotools/factorio:stable",
				isDefault: true,
			},
		],
		variables: [
			{
				id: "var-fa-save",
				name: "Save name",
				description: "The map file to load or create.",
				envVariable: "SAVE_NAME",
				defaultValue: "world",
				type: "text",
				required: true,
				options: [],
				access: "editable",
			},
			{
				id: "var-fa-autosave",
				name: "Autosave interval",
				description: "Minutes between autosaves.",
				envVariable: "AUTOSAVE_INTERVAL",
				defaultValue: "10",
				type: "number",
				required: false,
				options: [],
				access: "editable",
			},
			{
				id: "var-fa-token",
				name: "Mod-portal token",
				description: "Used to download mods from the Factorio mod portal.",
				envVariable: "MOD_PORTAL_TOKEN",
				defaultValue: null,
				type: "text",
				required: false,
				options: [],
				access: "secret",
			},
		],
		startupCommand:
			"factorio --start-server /mnt/server/saves/{{SAVE_NAME}}.zip --autosave-interval {{AUTOSAVE_INTERVAL}}",
		stopType: "signal",
		stopValue: "SIGINT",
		doneMarkers: [{ kind: "string", value: "Starting RCON interface" }],
		installScript:
			"#!/bin/bash\n# Pull the latest stable Factorio headless build into /mnt/server.\ncurl -sSL https://factorio.example/get-download/stable/headless/linux64 | tar -xJ -C /mnt/server --strip-components=1\n",
		installContainerImage: "ghcr.io/pterodactyl/installers:debian",
		installEntrypoint: "bash",
		configFiles: [],
		features: [],
	},
	{
		id: "a8b9c0d1-5e6f-4a7b-8c8d-9e0f1a2b3c4d",
		name: "Rust - Staff Event",
		slug: "rust-staff-event",
		iconUrl: null,
		summary: "Forked Rust build with our plugin pack and weekly wipe schedule.",
		description:
			"Our internal Rust build for staff events: the oxide plugin pack baked in and a weekly wipe. Customized from the official Rust template.",
		category: "Survival",
		official: false,
		origin: "fork",
		status: "published",
		version: 5,
		serverCount: 1,
		updatedAt: "Jun 09, 2026",
		parentName: "Rust",
		images: [
			{
				id: "img-rust",
				label: "SteamCMD (Debian)",
				image: "ghcr.io/pterodactyl/yolks:steamcmd_debian",
				isDefault: true,
			},
		],
		variables: [
			{
				id: "var-rust-hostname",
				name: "Server name",
				description: "Shown in the Rust server browser.",
				envVariable: "HOSTNAME",
				defaultValue: "Staff Event - Wipe Fridays",
				type: "text",
				required: true,
				options: [],
				access: "editable",
			},
			{
				id: "var-rust-worldsize",
				name: "World size",
				description: "Map size in metres (1000–6000).",
				envVariable: "WORLD_SIZE",
				defaultValue: "3500",
				type: "number",
				required: true,
				options: [],
				access: "editable",
			},
			{
				id: "var-rust-rcon",
				name: "RCON password",
				description: "Remote-console admin password.",
				envVariable: "RCON_PASS",
				defaultValue: null,
				type: "text",
				required: true,
				options: [],
				access: "secret",
			},
		],
		startupCommand:
			'./RustDedicated -batchmode +server.hostname "{{HOSTNAME}}" +server.worldsize {{WORLD_SIZE}} +rcon.password {{RCON_PASS}}',
		stopType: "command",
		stopValue: "quit",
		doneMarkers: [{ kind: "string", value: "Server startup complete" }],
		installScript:
			"#!/bin/bash\nsteamcmd +force_install_dir /mnt/server +login anonymous +app_update 258550 validate +quit\n# Drop in our staff plugin pack.\ncp -r /tmp/oxide-pack/* /mnt/server/oxide/plugins/\n",
		installContainerImage: "ghcr.io/pterodactyl/installers:debian",
		installEntrypoint: "bash",
		configFiles: [],
		features: [],
	},
	{
		id: "b9c0d1e2-6f7a-4b8c-9d9e-0f1a2b3c4d5e",
		name: "Minecraft: Modded (Forge)",
		slug: "minecraft-modded-forge",
		iconUrl: null,
		summary: "Forge loader sized for large modpacks; community-curated pack.",
		description:
			"A Forge server tuned for heavy modpacks, with extra heap headroom and a longer startup window. Imported from a community template; still in review before it's published.",
		category: "Minecraft",
		official: false,
		origin: "import",
		status: "draft",
		version: 1,
		serverCount: 0,
		updatedAt: "Jun 02, 2026",
		parentName: null,
		images: [
			{
				id: "img-forge",
				label: "Java 17",
				image: "ghcr.io/pterodactyl/yolks:java_17",
				isDefault: true,
			},
		],
		variables: [
			{
				id: "var-forge-version",
				name: "Forge version",
				description: "Forge installer version to use.",
				envVariable: "FORGE_VERSION",
				defaultValue: "47.2.0",
				type: "text",
				required: true,
				options: [],
				access: "editable",
			},
			{
				id: "var-forge-mem",
				name: "Heap headroom",
				description: "Extra MB of heap for large packs.",
				envVariable: "EXTRA_HEAP",
				defaultValue: "2048",
				type: "number",
				required: false,
				options: [],
				access: "read-only",
			},
		],
		startupCommand:
			"java -Xmx{{SERVER_MEMORY}}M -jar forge-{{FORGE_VERSION}}.jar nogui",
		stopType: "command",
		stopValue: "stop",
		doneMarkers: [{ kind: "string", value: "Done (" }],
		installScript:
			'#!/bin/bash\ncd /mnt/server\ncurl -sSL -o forge-installer.jar "https://maven.example/forge/{{FORGE_VERSION}}/installer.jar"\njava -jar forge-installer.jar --installServer\necho "eula=true" > eula.txt\n',
		installContainerImage: "ghcr.io/pterodactyl/installers:java",
		installEntrypoint: "bash",
		configFiles: [],
		features: [{ key: "minecraft:mods" }],
	},
	{
		id: "c0d1e2f3-7a8b-4c9d-8e0f-1a2b3c4d5e6f",
		name: "Terraria (TShock)",
		slug: "terraria-tshock",
		iconUrl: null,
		summary: "TShock-powered Terraria with a REST admin API and slot control.",
		description:
			"A TShock-powered Terraria server with the REST admin API. Set the world file and player slots and you're ready.",
		category: "Sandbox",
		official: false,
		origin: "scratch",
		status: "published",
		version: 1,
		serverCount: 1,
		updatedAt: "Jun 11, 2026",
		parentName: null,
		images: [
			{
				id: "img-tshock",
				label: "Mono (Debian)",
				image: "ghcr.io/pterodactyl/yolks:mono_latest",
				isDefault: true,
			},
		],
		variables: [
			{
				id: "var-ts-world",
				name: "World file",
				description: "The .wld to load.",
				envVariable: "WORLD_FILE",
				defaultValue: "world.wld",
				type: "text",
				required: true,
				options: [],
				access: "editable",
			},
			{
				id: "var-ts-maxplayers",
				name: "Max players",
				description: "Slot count.",
				envVariable: "MAX_PLAYERS",
				defaultValue: "8",
				type: "number",
				required: false,
				options: [],
				access: "editable",
			},
		],
		startupCommand:
			"mono TShock.Server.exe -world /mnt/server/worlds/{{WORLD_FILE}} -maxplayers {{MAX_PLAYERS}}",
		stopType: "command",
		stopValue: "exit",
		doneMarkers: [{ kind: "string", value: "Server started" }],
		installScript: "",
		installContainerImage: "",
		installEntrypoint: "bash",
		configFiles: [],
		features: [],
	},
	{
		id: "d1e2f3a4-8b9c-4d0e-9f1a-2b3c4d5e6f70",
		name: "CS:GO Competitive",
		slug: "csgo-competitive",
		iconUrl: null,
		summary: "Legacy competitive config; superseded by our CS2 template.",
		description:
			"The old competitive CS:GO config. Archived now that CS2 has replaced it; kept so existing servers still resolve their template.",
		category: "FPS",
		official: false,
		origin: "scratch",
		status: "archived",
		version: 4,
		serverCount: 0,
		updatedAt: "Feb 18, 2026",
		parentName: null,
		images: [
			{
				id: "img-csgo",
				label: "SteamCMD (Debian)",
				image: "ghcr.io/pterodactyl/yolks:steamcmd_debian",
				isDefault: true,
			},
		],
		variables: [
			{
				id: "var-csgo-tickrate",
				name: "Tickrate",
				description: "Server tickrate.",
				envVariable: "TICKRATE",
				defaultValue: "128",
				type: "select",
				required: true,
				options: ["64", "128"],
				access: "editable",
			},
			{
				id: "var-csgo-gslt",
				name: "Game server token",
				description: "Steam Game Server Login Token.",
				envVariable: "GSLT",
				defaultValue: null,
				type: "text",
				required: true,
				options: [],
				access: "secret",
			},
		],
		startupCommand:
			"./srcds_run -game csgo -tickrate {{TICKRATE}} +sv_setsteamaccount {{GSLT}}",
		stopType: "signal",
		stopValue: "SIGINT",
		doneMarkers: [{ kind: "string", value: "GC Connection established" }],
		installScript:
			"#!/bin/bash\nsteamcmd +force_install_dir /mnt/server +login anonymous +app_update 740 validate +quit\n",
		installContainerImage: "ghcr.io/pterodactyl/installers:debian",
		installEntrypoint: "bash",
		configFiles: [],
		features: [{ key: "steam:gslt" }],
	},
	{
		id: "e2f3a4b5-9c0d-4e1f-8a2b-3c4d5e6f7081",
		name: "PostgreSQL",
		slug: "postgresql",
		iconUrl: null,
		summary: "Postgres relational database, managed from the SQL Browser.",
		description:
			"The official PostgreSQL database. Set a superuser password and it's ready. Turn on the SQL Browser add-on to create databases, users, and tables from the panel.",
		category: "Database",
		official: true,
		origin: "official",
		status: "published",
		version: 4,
		serverCount: 1,
		updatedAt: "Jun 02, 2026",
		parentName: null,
		images: [
			{
				id: "img-pg-16",
				label: "PostgreSQL 16",
				image: "postgres:16-alpine",
				isDefault: true,
			},
			{
				id: "img-pg-15",
				label: "PostgreSQL 15",
				image: "postgres:15-alpine",
				isDefault: false,
			},
		],
		variables: [
			{
				id: "var-pg-pass",
				name: "Superuser password",
				description: "Password for the postgres superuser.",
				envVariable: "POSTGRES_PASSWORD",
				defaultValue: null,
				type: "text",
				required: true,
				options: [],
				access: "secret",
			},
		],
		startupCommand: "postgres",
		stopType: "signal",
		stopValue: "SIGINT",
		doneMarkers: [
			{
				kind: "string",
				value: "database system is ready to accept connections",
			},
		],
		installScript: "",
		installContainerImage: "",
		installEntrypoint: "bash",
		configFiles: [],
		features: [{ key: "database:browser" }],
	},
	{
		id: "f3a4b5c6-0d1e-4f2a-9b3c-4d5e6f708192",
		name: "MySQL",
		slug: "mysql",
		iconUrl: null,
		summary: "MySQL relational database, managed from the SQL Browser.",
		description:
			"The official MySQL database. Set the root password and it's ready. Turn on the SQL Browser add-on to create databases, users, and tables from the panel.",
		category: "Database",
		official: true,
		origin: "official",
		status: "published",
		version: 3,
		serverCount: 1,
		updatedAt: "May 24, 2026",
		parentName: null,
		images: [
			{
				id: "img-mysql-84",
				label: "MySQL 8.4 LTS",
				image: "mysql:8.4",
				isDefault: true,
			},
			{
				id: "img-mysql-80",
				label: "MySQL 8.0",
				image: "mysql:8.0",
				isDefault: false,
			},
		],
		variables: [
			{
				id: "var-my-root",
				name: "Root password",
				description: "Password for the MySQL root user.",
				envVariable: "MYSQL_ROOT_PASSWORD",
				defaultValue: null,
				type: "text",
				required: true,
				options: [],
				access: "secret",
			},
		],
		startupCommand: "mysqld",
		stopType: "signal",
		stopValue: "SIGTERM",
		doneMarkers: [{ kind: "string", value: "ready for connections" }],
		installScript: "",
		installContainerImage: "",
		installEntrypoint: "bash",
		configFiles: [],
		features: [{ key: "database:browser" }],
	},
	{
		id: "a4b5c6d7-1e2f-4a3b-8c4d-5e6f708192a3",
		name: "MariaDB",
		slug: "mariadb",
		iconUrl: null,
		summary: "MariaDB, a drop-in MySQL replacement, from the SQL Browser.",
		description:
			"MariaDB, the community-developed MySQL fork. Set the root password and it's ready. Turn on the SQL Browser add-on to create databases, users, and tables from the panel.",
		category: "Database",
		official: true,
		origin: "official",
		status: "published",
		version: 2,
		serverCount: 0,
		updatedAt: "May 18, 2026",
		parentName: null,
		images: [
			{
				id: "img-maria-114",
				label: "MariaDB 11.4 LTS",
				image: "mariadb:11.4",
				isDefault: true,
			},
			{
				id: "img-maria-1011",
				label: "MariaDB 10.11 LTS",
				image: "mariadb:10.11",
				isDefault: false,
			},
		],
		variables: [
			{
				id: "var-maria-root",
				name: "Root password",
				description: "Password for the MariaDB root user.",
				envVariable: "MARIADB_ROOT_PASSWORD",
				defaultValue: null,
				type: "text",
				required: true,
				options: [],
				access: "secret",
			},
		],
		startupCommand: "mariadbd",
		stopType: "signal",
		stopValue: "SIGTERM",
		doneMarkers: [{ kind: "string", value: "ready for connections" }],
		installScript: "",
		installContainerImage: "",
		installEntrypoint: "bash",
		configFiles: [],
		features: [{ key: "database:browser" }],
	},
	{
		id: "b5c6d7e8-2f3a-4b4c-9d5e-6f708192a3b4",
		name: "Redis",
		slug: "redis",
		iconUrl: null,
		summary: "In-memory key-value store for caching, sessions, and queues.",
		description:
			"Redis, an in-memory data store. Set a password and a memory limit; it's tuned to evict the least-recently-used keys when full. A fast fit for caches, sessions, and lightweight queues.",
		category: "Database",
		official: true,
		origin: "official",
		status: "published",
		version: 3,
		serverCount: 1,
		updatedAt: "Jun 05, 2026",
		parentName: null,
		images: [
			{
				id: "img-redis-74",
				label: "Redis 7.4",
				image: "redis:7.4-alpine",
				isDefault: true,
			},
			{
				id: "img-redis-72",
				label: "Redis 7.2",
				image: "redis:7.2-alpine",
				isDefault: false,
			},
		],
		variables: [
			{
				id: "var-redis-pass",
				name: "Password",
				description: "Required to connect (sets requirepass).",
				envVariable: "REDIS_PASSWORD",
				defaultValue: null,
				type: "text",
				required: true,
				options: [],
				access: "secret",
			},
			{
				id: "var-redis-mem",
				name: "Memory limit",
				description: "Max memory before keys are evicted.",
				envVariable: "MAXMEMORY",
				defaultValue: "256mb",
				type: "text",
				required: false,
				options: [],
				access: "editable",
			},
		],
		startupCommand:
			"redis-server --requirepass {{REDIS_PASSWORD}} --maxmemory {{MAXMEMORY}} --maxmemory-policy allkeys-lru",
		stopType: "signal",
		stopValue: "SIGTERM",
		doneMarkers: [{ kind: "string", value: "Ready to accept connections" }],
		installScript: "",
		installContainerImage: "",
		installEntrypoint: "bash",
		configFiles: [],
		features: [{ key: "database:browser" }],
	},
	{
		id: "c6d7e8f9-3a4b-4c5d-8e6f-708192a3b4c5",
		name: "MongoDB",
		slug: "mongodb",
		iconUrl: null,
		summary: "Document database for flexible, JSON-like data.",
		description:
			"MongoDB, a document database. Set a root username and password and it's ready; authentication is on by default. Turn on the Document Browser add-on to browse databases, collections, and documents from the panel.",
		category: "Database",
		official: true,
		origin: "official",
		status: "published",
		version: 2,
		serverCount: 1,
		updatedAt: "May 30, 2026",
		parentName: null,
		images: [
			{
				id: "img-mongo-70",
				label: "MongoDB 7.0",
				image: "mongo:7.0",
				isDefault: true,
			},
			{
				id: "img-mongo-60",
				label: "MongoDB 6.0",
				image: "mongo:6.0",
				isDefault: false,
			},
		],
		variables: [
			{
				id: "var-mongo-user",
				name: "Root username",
				description: "The root user to create.",
				envVariable: "MONGO_INITDB_ROOT_USERNAME",
				defaultValue: "root",
				type: "text",
				required: true,
				options: [],
				access: "editable",
			},
			{
				id: "var-mongo-pass",
				name: "Root password",
				description: "Password for the root user.",
				envVariable: "MONGO_INITDB_ROOT_PASSWORD",
				defaultValue: null,
				type: "text",
				required: true,
				options: [],
				access: "secret",
			},
		],
		startupCommand: "mongod --auth",
		stopType: "signal",
		stopValue: "SIGTERM",
		doneMarkers: [{ kind: "string", value: "Waiting for connections" }],
		installScript: "",
		installContainerImage: "",
		installEntrypoint: "bash",
		configFiles: [],
		features: [{ key: "database:browser" }],
	},
];

// — Drives / Allocations / Firewall (daemon-derived, per node) —————————————————

// Only the reporting (online/unhealthy) nodes have drives; offline/pending nodes
// show their tab's stale/empty state instead.
export const DRIVES: DriveRow[] = [
	{
		id: "5a1b2c3d-1111-4a22-8b33-aa01bb02cc03",
		nodeId: NODE_ID.atlas,
		device: "/dev/nvme0n1p1",
		model: "Samsung PM9A3",
		sizeBytes: 128 * GiB,
		usedBytes: 41 * GiB,
		filesystem: "ext4",
		mountpoint: "/",
		isDataTarget: false,
	},
	{
		id: "5a1b2c3d-2222-4a22-8b33-aa01bb02cc04",
		nodeId: NODE_ID.atlas,
		device: "/dev/nvme1n1",
		model: "Samsung PM9A3 1.9TB",
		sizeBytes: 2 * TiB,
		usedBytes: 1 * TiB,
		filesystem: "ext4",
		mountpoint: "/var/lib/cookiepanel",
		isDataTarget: true,
	},
	{
		id: "5a1b2c3d-3333-4a22-8b33-aa01bb02cc05",
		nodeId: NODE_ID.atlas,
		device: "/dev/sda",
		model: "Seagate IronWolf 4TB",
		sizeBytes: 4 * TiB,
		usedBytes: null,
		filesystem: null,
		mountpoint: null,
		isDataTarget: false,
	},
	{
		id: "6b2c3d4e-1111-4b33-9c44-bb02cc03dd04",
		nodeId: NODE_ID.valhalla,
		device: "/dev/sda2",
		model: "Crucial MX500",
		sizeBytes: 256 * GiB,
		usedBytes: 52 * GiB,
		filesystem: "ext4",
		mountpoint: "/",
		isDataTarget: false,
	},
	{
		id: "6b2c3d4e-2222-4b33-9c44-bb02cc03dd05",
		nodeId: NODE_ID.valhalla,
		device: "/dev/sdb1",
		model: "WD Red 1TB",
		sizeBytes: 1 * TiB,
		usedBytes: 700 * GiB,
		filesystem: "xfs",
		mountpoint: "/data",
		isDataTarget: true,
	},
	{
		id: "7c3d4e5f-1111-4c44-8d55-cc03dd04ee05",
		nodeId: NODE_ID.orion,
		device: "/dev/nvme0n1p1",
		model: "WD Black SN850X",
		sizeBytes: 1 * GiB,
		usedBytes: 0.3 * GiB,
		filesystem: "ext4",
		mountpoint: "/boot",
		isDataTarget: false,
	},
	{
		id: "7c3d4e5f-2222-4c44-8d55-cc03dd04ee06",
		nodeId: NODE_ID.orion,
		device: "/dev/nvme0n1p2",
		model: "WD Black SN850X",
		sizeBytes: 200 * GiB,
		usedBytes: 64 * GiB,
		filesystem: "ext4",
		mountpoint: "/",
		isDataTarget: false,
	},
	{
		id: "7c3d4e5f-3333-4c44-8d55-cc03dd04ee07",
		nodeId: NODE_ID.orion,
		device: "/dev/nvme1n1",
		model: "Micron 7450 3.84TB",
		sizeBytes: 4 * TiB,
		usedBytes: 1.5 * TiB,
		filesystem: "ext4",
		mountpoint: "/var/lib/cookiepanel",
		isDataTarget: true,
	},
	{
		id: "8d4e5f6a-1111-4d55-9e66-dd04ee05ff06",
		nodeId: NODE_ID.helios,
		device: "/dev/sda1",
		model: "Kingston DC600M",
		sizeBytes: 500 * GiB,
		usedBytes: 470 * GiB,
		filesystem: "ext4",
		mountpoint: "/",
		isDataTarget: false,
	},
	{
		id: "8d4e5f6a-2222-4d55-9e66-dd04ee05ff07",
		nodeId: NODE_ID.helios,
		device: "/dev/sdb1",
		model: "Kingston DC600M",
		sizeBytes: 500 * GiB,
		usedBytes: 180 * GiB,
		filesystem: "ext4",
		mountpoint: "/data",
		isDataTarget: true,
	},
];
